<?php
/**
 * Implements hook_preprocess_HOOK()
 */
function ulf_theme_mods_preprocess_node(&$variables) {
  // Check offer types for special needs.
  if (!empty($variables['field_offer_type'])) {
    foreach($variables['field_offer_type'] as $offer_type) {
      if (isset($offer_type['taxonomy_term'])) {
        if($offer_type['taxonomy_term']->name =='Børn og unge med særlige behov') {
          $variables['is_special_needs_type'] = TRUE;
        }
        else {
          $variables['is_special_needs_type'] = FALSE;
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_user_profile().
 *
 * @param $variables
 *   Available variables.
 */
function ulf_theme_mods_preprocess_user_profile(&$variables) {
  // Enable a view for user profile templates.
  $variables['content_by_user'] = views_embed_view('ulf_content_by_user', 'block_1');
  $variables['content_by_user_courses'] = views_embed_view('ulf_content_by_user', 'block_2');
}