<?php
/**
 * @file
 * ulf_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function ulf_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-92SISZnd7Yj1J2PeHXxO1kL3SMs2UNnN'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '92SISZnd7Yj1J2PeHXxO1kL3SMs2UNnN',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -8,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-BOiTNRybGi0EqoVhsAPq2yw0QL1EVZo1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BOiTNRybGi0EqoVhsAPq2yw0QL1EVZo1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -6,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-EPDhVXDTO2ass7J8dUM6PGyo1bJM6bDR'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'EPDhVXDTO2ass7J8dUM6PGyo1bJM6bDR',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -13,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Fp1e9iIvE1huqf8Y3PBXn19keqxmYQCy'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Fp1e9iIvE1huqf8Y3PBXn19keqxmYQCy',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -10,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Gn0lQmbjEvPs4JPPQHOogWsCb3Tt1r8U'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Gn0lQmbjEvPs4JPPQHOogWsCb3Tt1r8U',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -1,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-I6hNUYS3jXnK8SD4alsVPluA48gO7NPz'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'I6hNUYS3jXnK8SD4alsVPluA48gO7NPz',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -5,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-JZV1EbSLtMsdx0hqmk1e5aiz3Hw1sH2p'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'JZV1EbSLtMsdx0hqmk1e5aiz3Hw1sH2p',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -3,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Px4eDQzQbAOQVD8FWUiBr1oLKW1qDPaC'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Px4eDQzQbAOQVD8FWUiBr1oLKW1qDPaC',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -11,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-U0TqlG0313vhigH1g5N3NkJkaIHQVFuS'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'U0TqlG0313vhigH1g5N3NkJkaIHQVFuS',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -15,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Yn3rDYEywSY6LqphNkdDhXzXULsEjNkC'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Yn3rDYEywSY6LqphNkdDhXzXULsEjNkC',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -20,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-f5jleT4wQqSvPAZwM4ccmbfz6FrzLQzC'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'f5jleT4wQqSvPAZwM4ccmbfz6FrzLQzC',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -14,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-jHiTLPKfFRWx0A3VS0o7UdExEMDvZA3G'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'jHiTLPKfFRWx0A3VS0o7UdExEMDvZA3G',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -18,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-jPSEnykO74th5EozWmGpclG7Dd7euxNN'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'jPSEnykO74th5EozWmGpclG7Dd7euxNN',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -17,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-sZSsaGJedCZ38yin8onDhbRjtJQH3g6C'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'sZSsaGJedCZ38yin8onDhbRjtJQH3g6C',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -9,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-sropn1R1PQh1vJZB1Z6wtaoRZmEeCOge'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'sropn1R1PQh1vJZB1Z6wtaoRZmEeCOge',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -4,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-tPuYoiknARWJHIIgVsBEfQdSO6vRHC0S'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'tPuYoiknARWJHIIgVsBEfQdSO6vRHC0S',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -12,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-uZZx02jgrO5f1YGSr50SSh4eNs1ORcWY'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'uZZx02jgrO5f1YGSr50SSh4eNs1ORcWY',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -2,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-v30lLxmCsdkS0BHMDmyFE0mYS5hkePNV'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'v30lLxmCsdkS0BHMDmyFE0mYS5hkePNV',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -16,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-vga1DhRgcg0BrGxTS3Gmzs1ZvkwvXo0t'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'vga1DhRgcg0BrGxTS3Gmzs1ZvkwvXo0t',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -7,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-zkQUMgh2adYg5SkgiravqOKciGZlFTxo'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'zkQUMgh2adYg5SkgiravqOKciGZlFTxo',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -19,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
