version: "3"

services:
  mariadb:
    image: mariadb:10.3
    ports:
      - '3306'
    volumes:
      - .docker/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db

  phpfpm:
    image: itkdev/php7.0-fpm:latest
    environment:
      - PHP_XDEBUG=${PHP_XDEBUG:-0}
      - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART:-0}
      - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST:-0.0.0.0}
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAIL=1
    depends_on:
      - mariadb
    volumes:
      - .:/app:delegated
      - drush-cache:/root/.drush

  ulf.docker.localhost:
    image: nginx:latest
    depends_on:
      - phpfpm
      - memcached
    ports:
      - '8080:8080'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated

  memcached:
    image: 'memcached:latest'
    ports:
      - '11211'
    environment:
      - MEMCACHED_CACHE_SIZE=64

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025"

  drush:
    image: itkdev/drush6:latest
    depends_on:
      - mariadb
    entrypoint:
      - drush
    volumes:
      - drush-cache:/root/.drush
      - ./:/app

  pretix:
    image: pretix/standalone:stable
    depends_on:
      - pretix_database
      - redis
      - mailhog
    ports:
      - "80"
    volumes:
      - ${PWD}/.docker/pretix/etc/pretix.cfg:/etc/pretix/pretix.cfg

  # Proxy to forward traffic on port 8000 to pretix (on port 80)
  pretix.docker.localhost:
    image: nginx:latest
    depends_on:
      - pretix
    ports:
      - '8081:8081'
    volumes:
      - ${PWD}/.docker/pretix/proxy.vhost.conf:/etc/nginx/conf.d/default.conf:ro

  pretix_database:
    image: mariadb:10.3
    ports:
      - '3306'
    volumes:
      - .docker/dumps/pretix:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: pretix
      MYSQL_PASSWORD: pretix
      MYSQL_DATABASE: pretix

  redis:
    image: redis:latest
    ports:
      - "6379"

# Drush cache volume to persist cache between runs.
volumes:
  drush-cache:
