<?php
/**
 * @file
 * Code for the Ulf registration_configuration feature.
 */

include_once 'ulf_registration_configuration.features.inc';

/**
 * Implements hook_form_alter().
 *
 * Modify forms related to registration.
 */
function ulf_registration_configuration_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['#node_edit_form']) && ($form['#node']->type == 'course' || $form['#node']->type == 'course_educators')) {
    $form['#group_children']['field_registration_form'] = 'group_signup';
  }

  if ($form_id == 'registration_form') {
    $form['who_is_registering']['#default_value'] = 'registration_registrant_type_me';
    $form['who_is_registering']['#access'] = FALSE;
    $form['user']['#access'] = FALSE;
    // Hide state on signup but show on change in backend.
    if(arg(0) == 'node') {
      $form['state']['#access'] = FALSE;
    }
    $form['actions']['cancel']['#access'] = FALSE;
  }

  if ($form_id == 'registration_entity_settings_form') {
    // We can't allow course providers to set from address.
    $form['settings']['from_address']['#access'] = FALSE;
  }
  
}

/**
 * Implements hook_admin_paths_alter().
 *
 * Set several paths to be displayed in admin theme.
 */
function ulf_registration_configuration_admin_paths_alter(&$paths) {
  $paths['node/*/registrations'] = TRUE;
  $paths['node/*/registrations/*'] = TRUE;
  $paths['registration/*'] = TRUE;
  $paths['registration/*/edit'] = TRUE;
}


/**
 * Implements hook_secure_permissions().
 *
 * Setup permissions related to registration.
 */
function ulf_registration_configuration_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'create signup registration',
      'create signup registration self'
    ),
    'authenticated user' => array(
      'create signup registration',
      'create signup registration self'
    ),
    'course provider' => array(
      'administer own signup registration',
      'view own signup registration',
      'create signup registration',
      'update own signup registration',
      'update any signup registration',
      'delete own signup registration',
      'create signup registration self',
      'edit signup registration state'
    ),
    'editor' => array(
      'administer signup registration',
      'administer own signup registration',
      'view signup registration',
      'view own signup registration',
      'update own signup registration',
      'update any signup registration',
      'delete own signup registration',
      'delete any signup registration',
      'create signup registration self',
      'edit signup registration state'
    ),
  );

  return isset($permissions[$role]) ? $permissions[$role] : NULL;
}
