<?php
/**
 * @file
 * ulf_taxonomies.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function ulf_taxonomies_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Multimedier',
    'description' => NULL,
    'format' => NULL,
    'weight' => 19,
    'uuid' => '0971107b-e3c1-4271-847a-f11f118a4142',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Biologi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 57,
    'uuid' => '0d635b85-62a5-42d2-918b-13568a3d6467',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Alsidig personlig udvikling',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 50,
    'uuid' => '0ed6fd69-6386-4885-83b3-d4271932e7db',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'HHX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 20,
    'uuid' => '10bc7b6e-29b3-4a58-b948-7475a89670eb',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kristendom',
    'description' => NULL,
    'format' => NULL,
    'weight' => 67,
    'uuid' => '14b63784-7ba4-4d40-8de8-b034f45a1155',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Dagtilbud',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '18824c90-f2f0-4734-9310-ed4ae77243ae',
    'vocabulary_machine_name' => 'target_group',
  );
  $terms[] = array(
    'name' => 'Psykologi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 5,
    'uuid' => '1ac2886d-9fbc-45bc-8df2-13b60f931f92',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '0. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => '1b3edbc3-53cc-4fd0-bfba-6e4de193d8ed',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Teknikfag',
    'description' => NULL,
    'format' => NULL,
    'weight' => 33,
    'uuid' => '1dcc40f3-2e47-4a68-a998-03bdf4b60f8d',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '2. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '1e1b9107-5755-47c4-8d8d-09f75a5dcf28',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Markedskommunikation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 12,
    'uuid' => '1e4ad175-952e-49be-afff-55601eb3e6b7',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Bioteknologi (forsøg)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 56,
    'uuid' => '20b86ff2-bd78-4435-8e7f-64b75be56fc9',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Idræt',
    'description' => NULL,
    'format' => NULL,
    'weight' => 78,
    'uuid' => '21211517-ab2a-4b1f-a78d-5e6b53a60a2f',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Naturvidenskabelig faggruppe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 3,
    'uuid' => '214ce233-7201-4e1a-aee9-861c7ea74f14',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Natur/teknik',
    'description' => NULL,
    'format' => NULL,
    'weight' => 10,
    'uuid' => '236183e4-b463-4a2e-a0f3-9a9e325421a2',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Teknologihistorie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 25,
    'uuid' => '246ff4f3-d3a1-40c1-b46b-7d2e7babe501',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '0 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '25a5e454-f086-45b5-a122-1fea816d31ed',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'HF',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 21,
    'uuid' => '26aed059-b358-47df-a8a9-f755671e5853',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '3 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '26e1ac50-e997-400e-8ca5-c0dd88d6de21',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Dramatik',
    'description' => NULL,
    'format' => NULL,
    'weight' => 38,
    'uuid' => '2ac60e93-a2b5-4e1a-8a77-82e2678e1889',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Filosofi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 45,
    'uuid' => '2bbb36fd-1e05-4ebb-8ace-7c0fc332741a',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Organisation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2e512cf1-0421-4ae2-a52f-d88b4c028927',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Latin',
    'description' => NULL,
    'format' => NULL,
    'weight' => 13,
    'uuid' => '35b0442f-fd7f-4823-8261-871d5e346ced',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Historie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 75,
    'uuid' => '35ee0357-005e-469d-9ee3-376e73810ae0',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '1 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '3d7dfa93-ef8d-4e60-9bb5-9407cb9133c4',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Datalogi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 41,
    'uuid' => '3de5dcd3-a4d5-460a-9151-582fc4d340b2',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Russisk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 6,
    'uuid' => '3eb1560e-95f4-4604-87fc-08d1adc10d22',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Erhvervsøkonomi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 46,
    'uuid' => '40cc9fe9-4e7b-4d99-af90-cde658f2c5b2',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Tysk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 23,
    'uuid' => '45805d04-0b76-45ee-a36b-a63f03d03dab',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Geografi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 73,
    'uuid' => '46899f2d-8078-4f67-aad7-fb7bfe1d685c',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '3. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 10,
    'uuid' => '4941e01e-9dc0-4e83-a147-a51e9fbfe5c6',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kulturhistorie og kulturarv',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4b2fd2d2-eb1d-49dc-b133-347aafd3021d',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Statik og styrkelære',
    'description' => NULL,
    'format' => NULL,
    'weight' => 31,
    'uuid' => '4c2ba0cf-6a57-42da-92cf-156e1abde278',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Afsætning',
    'description' => NULL,
    'format' => NULL,
    'weight' => 80,
    'uuid' => '4d2792ef-2eb7-485c-a1b5-486cdd5bad35',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Materialeteknologi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 15,
    'uuid' => '4f7bc368-611e-4f78-b9e3-51220dff9e9e',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Fransk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 58,
    'uuid' => '5302dc86-cafd-4c27-bf84-3638a759ba03',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '6. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 13,
    'uuid' => '540acde5-2d57-4eab-b44d-9150233c1be2',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Naturgeografi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 9,
    'uuid' => '59234bc1-586f-41a8-96be-76e9561cc775',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '10. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 17,
    'uuid' => '59b279fe-6430-4895-896e-ae0e931ee9f2',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'STX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 18,
    'uuid' => '5c79aa0c-dc12-4eba-b9a4-b1ee9d779d86',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Samtidshistorie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 21,
    'uuid' => '5c7a4a33-8083-41c4-863b-e499bd5cc641',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Kemi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 64,
    'uuid' => '5ee9c85d-0ca2-46a2-a6f0-0a5f1db55e12',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Kulturelle udtryksformer og værdier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 36,
    'uuid' => '613027b2-7e20-4d6f-a8c9-5ab7b4a08e13',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Studieområdet',
    'description' => NULL,
    'format' => NULL,
    'weight' => 35,
    'uuid' => '61cf6112-fb64-4a9a-a924-6a6479a3db84',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '2 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '65d2a9c0-57f3-43f8-8cb5-cf2ee04611a9',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kultur- og samfundsfaggruppen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 37,
    'uuid' => '6637839a-5d58-49e6-8621-3a44f936395c',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Håndarbejde',
    'description' => NULL,
    'format' => NULL,
    'weight' => 71,
    'uuid' => '66bcc887-f31a-4181-b7d2-5a4d684f56ba',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Astronomi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 53,
    'uuid' => '66cba494-685d-440c-8961-98d0da68a59e',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Fysik',
    'description' => NULL,
    'format' => NULL,
    'weight' => 59,
    'uuid' => '67ab6936-f5a6-4a34-8897-a73a386711da',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Sløjd',
    'description' => NULL,
    'format' => NULL,
    'weight' => 30,
    'uuid' => '6ac41c06-332b-46e2-b7c3-90d233b0f054',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Matematik',
    'description' => NULL,
    'format' => NULL,
    'weight' => 11,
    'uuid' => '6c9fbba0-1bca-488f-bb4f-08a907122442',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Sproglig udvikling',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 27,
    'uuid' => '6cde5f63-390a-4422-a50f-f821115b57fb',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Kunst, arkitektur og design',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6d486dc2-d02f-4fe2-a0c0-08659ac5fa36',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Forløb',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6ddf328e-e644-47ba-b94c-40b1c1c7bf02',
    'vocabulary_machine_name' => 'offer_type',
  );
  $terms[] = array(
    'name' => 'Studieretningsprojektet',
    'description' => NULL,
    'format' => NULL,
    'weight' => 34,
    'uuid' => '75557125-f5b7-40cc-bacd-576aef840858',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Samfundsfag',
    'description' => NULL,
    'format' => NULL,
    'weight' => 20,
    'uuid' => '75762068-aaed-4753-98d6-8ea8398d5ece',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Religion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 8,
    'uuid' => '75d5aeb3-e9a4-4b6e-bc74-18d229c8f809',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Fysik/kemi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 74,
    'uuid' => '79e0603f-18f8-4a51-9f62-b3f7222f4119',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Dans',
    'description' => NULL,
    'format' => NULL,
    'weight' => 55,
    'uuid' => '7ac3c7ce-c1ba-4135-aacc-2b7bd7337b7c',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Tværfaglige tilbud',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8002d3cc-f51a-4895-a08a-ffb18166fbc9',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Musik',
    'description' => NULL,
    'format' => NULL,
    'weight' => 18,
    'uuid' => '811369c8-ed12-480c-93a5-0bab047c66f7',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Idræt og bevægelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8631fc63-25c3-41d8-a945-392602ab8d50',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Idehistorie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 79,
    'uuid' => '869ff0d4-07ad-42d2-9f24-a856b6effb0d',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Tyrkisk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 24,
    'uuid' => '87b15282-0260-4e7c-84f7-023c48d78269',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Erhvervsret',
    'description' => NULL,
    'format' => NULL,
    'weight' => 43,
    'uuid' => '87b4aa99-fd17-4d29-b36f-aaad144082d1',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Almen sprogforståelse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 52,
    'uuid' => '89e432ef-043d-4b0a-831b-fc27e983d0e6',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Sociale kompetencer',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 29,
    'uuid' => '8ab092f1-6ad2-4d15-8445-889269889f04',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Hjemkundskab',
    'description' => NULL,
    'format' => NULL,
    'weight' => 76,
    'uuid' => '8bc21aad-fc6c-4a6a-8e8f-3a7f6818ad05',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Naturvidenskab',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8f029972-cf4b-4d60-8b4b-bd40335cf4bb',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Japansk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 60,
    'uuid' => '8f2d3f6a-5546-4a45-a304-2cc5904c0430',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Natur og naturfænomener',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 17,
    'uuid' => '9048dcc5-22f1-4bcb-acd6-9147b7dc7814',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'It',
    'description' => NULL,
    'format' => NULL,
    'weight' => 62,
    'uuid' => '93516c2a-0444-4ddd-8704-22c0e59f0246',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '1. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => '95bc7a90-bfd1-4ac4-b00e-3edbf958fe69',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kinesisk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 65,
    'uuid' => '96fe55c9-1b0e-437b-a9ee-87183ada5e0b',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Kulturforståelse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 14,
    'uuid' => '9f1e7c3f-72b2-412b-b19d-31dd8f64110c',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Spansk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 28,
    'uuid' => 'a0e8c41b-866c-46ff-ad71-3f4914642a35',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Teknologi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 26,
    'uuid' => 'a1574feb-edbd-442b-8579-7a52c4d8c48d',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '5. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 12,
    'uuid' => 'a69b46be-77eb-4fdf-bcc4-b65ab163f5ce',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Engelsk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 42,
    'uuid' => 'a9f4e7bc-86e6-4641-a8fc-1932e273ada2',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Finansiering',
    'description' => NULL,
    'format' => NULL,
    'weight' => 44,
    'uuid' => 'aa314cda-a600-4a16-9f45-440ebf53b80e',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Film, musik, teater og dans',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ab70ca4c-35b3-4714-85be-23dee6ad4ad0',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Italiensk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 61,
    'uuid' => 'ad9b3f1e-724c-4ac1-a954-67140238b3e5',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Billedkunst',
    'description' => NULL,
    'format' => NULL,
    'weight' => 54,
    'uuid' => 'af318feb-b2b8-4c17-85e1-619529cfbe80',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Statistik',
    'description' => NULL,
    'format' => NULL,
    'weight' => 32,
    'uuid' => 'aff53262-aae6-40da-927f-80dc5df76066',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Mediefag (film og tv)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 16,
    'uuid' => 'b06e86a2-d47e-4cae-ba89-4ca2d35b4026',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Arabisk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 49,
    'uuid' => 'b4419258-569c-4a5b-99f5-1693112772be',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '8. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 15,
    'uuid' => 'b4b966b5-7404-4c51-b38d-738f16649e8b',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kommunikation/it',
    'description' => NULL,
    'format' => NULL,
    'weight' => 68,
    'uuid' => 'b68633f5-14ef-4aef-bc43-9b92f7f1a9d4',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Dansk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 48,
    'uuid' => 'b987ada5-9096-4b16-9265-cda6c617aa1a',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '7. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 14,
    'uuid' => 'bd6809f5-5e83-4bcd-87b4-e2ee84a615e8',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Innovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 70,
    'uuid' => 'c4fb3ea3-d304-4c48-8770-4e36e90e8211',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Besøg',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c5453384-2d8f-4b75-b6b0-21b00fe009a4',
    'vocabulary_machine_name' => 'offer_type',
  );
  $terms[] = array(
    'name' => 'Drama',
    'description' => NULL,
    'format' => NULL,
    'weight' => 39,
    'uuid' => 'c675d5fe-23d0-437f-b025-05b17f565494',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Design',
    'description' => NULL,
    'format' => NULL,
    'weight' => 40,
    'uuid' => 'c7d77337-328c-4f09-9d19-180481040e17',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '6 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => 'd0a3b591-cdc7-4238-9d09-1680fe485762',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'International teknologi og kultur',
    'description' => NULL,
    'format' => NULL,
    'weight' => 69,
    'uuid' => 'd17d6860-286f-45ef-a79d-8d97887a7d19',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'HTX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 19,
    'uuid' => 'd2ec93f5-5c98-452c-8420-8873041c9d0e',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Krop og bevægelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 66,
    'uuid' => 'd53bd594-8c4c-4c0a-9489-9cf362d6ab3b',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Almen studieforberedelse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 51,
    'uuid' => 'd6e6c75e-ff71-4a93-a9a7-2991bb388b9e',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Retorik',
    'description' => NULL,
    'format' => NULL,
    'weight' => 7,
    'uuid' => 'daaee554-ec59-4a0b-9eaa-2a7c54583abe',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Grundskole',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dd78f109-e5ae-43af-80ef-d6a4f5b1029e',
    'vocabulary_machine_name' => 'target_group',
  );
  $terms[] = array(
    'name' => 'Informationsteknologi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 77,
    'uuid' => 'ddf23e00-0dec-4513-8935-f08865325618',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '5 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => 'e09b737c-cb61-4070-acfa-4b109dce6d83',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Dansk som andetsprog (forsøg)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 47,
    'uuid' => 'e13d1281-d4b3-4298-9cf4-bf076d82ff25',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Græsk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 72,
    'uuid' => 'e6ad0da0-07f6-4107-be7a-33c72e9e1b20',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Natur og friluftsliv',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e7293649-6773-48be-8fb2-293057d1ef0f',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'International økonomi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 63,
    'uuid' => 'e7532c2e-6c4f-4d99-8081-b0d97024af6e',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '9. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 16,
    'uuid' => 'ea8e1b64-6593-4f5e-b2a7-a2546e4125ec',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Virksomhedsøkonomi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 22,
    'uuid' => 'eccaa8b7-34e5-4187-82c9-eb6643bf7676',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Naturvidenskabeligt grundforløb',
    'description' => NULL,
    'format' => NULL,
    'weight' => 2,
    'uuid' => 'ed470347-bfa5-4d86-870f-720bef9951ec',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '4 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => 'eea18b3b-d816-4b4f-b66f-869d112a1019',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '4. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 11,
    'uuid' => 'f507a1f0-cfa6-499d-9a6a-1eca012035fb',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Programmering',
    'description' => NULL,
    'format' => NULL,
    'weight' => 4,
    'uuid' => 'fba7dc36-80a9-4597-b79c-e30aa8c5826a',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Oldtidskundskab',
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => 'fd1211b4-6e60-4334-a75b-017f2532ce11',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Ungdomsuddannelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ff21ca24-95c3-424d-97b4-0c9e5aed6eb8',
    'vocabulary_machine_name' => 'target_group',
  );
  return $terms;
}
