<?php
/**
 * @file
 * ulf_taxonomies.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function ulf_taxonomies_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'HHX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 20,
    'uuid' => '10bc7b6e-29b3-4a58-b948-7475a89670eb',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Dagtilbud',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '18824c90-f2f0-4734-9310-ed4ae77243ae',
    'vocabulary_machine_name' => 'target_group',
  );
  $terms[] = array(
    'name' => '0. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => '1b3edbc3-53cc-4fd0-bfba-6e4de193d8ed',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '2. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '1e1b9107-5755-47c4-8d8d-09f75a5dcf28',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '0 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '25a5e454-f086-45b5-a122-1fea816d31ed',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'HF',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 21,
    'uuid' => '26aed059-b358-47df-a8a9-f755671e5853',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '3 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '26e1ac50-e997-400e-8ca5-c0dd88d6de21',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '1 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '3d7dfa93-ef8d-4e60-9bb5-9407cb9133c4',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '3. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 10,
    'uuid' => '4941e01e-9dc0-4e83-a147-a51e9fbfe5c6',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kulturhistorie og kulturarv',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4b2fd2d2-eb1d-49dc-b133-347aafd3021d',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => '6. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 13,
    'uuid' => '540acde5-2d57-4eab-b44d-9150233c1be2',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '10. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 17,
    'uuid' => '59b279fe-6430-4895-896e-ae0e931ee9f2',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'STX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 18,
    'uuid' => '5c79aa0c-dc12-4eba-b9a4-b1ee9d779d86',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '2 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '65d2a9c0-57f3-43f8-8cb5-cf2ee04611a9',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kunst, arkitektur og design',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6d486dc2-d02f-4fe2-a0c0-08659ac5fa36',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Forløb',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6ddf328e-e644-47ba-b94c-40b1c1c7bf02',
    'vocabulary_machine_name' => 'offer_type',
  );
  $terms[] = array(
    'name' => 'Tværfaglige tilbud',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8002d3cc-f51a-4895-a08a-ffb18166fbc9',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Idræt og bevægelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8631fc63-25c3-41d8-a945-392602ab8d50',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Naturvidenskab',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8f029972-cf4b-4d60-8b4b-bd40335cf4bb',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => '1. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => '95bc7a90-bfd1-4ac4-b00e-3edbf958fe69',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '5. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 12,
    'uuid' => 'a69b46be-77eb-4fdf-bcc4-b65ab163f5ce',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Film, musik, teater og dans',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ab70ca4c-35b3-4714-85be-23dee6ad4ad0',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => '8. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 15,
    'uuid' => 'b4b966b5-7404-4c51-b38d-738f16649e8b',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '7. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 14,
    'uuid' => 'bd6809f5-5e83-4bcd-87b4-e2ee84a615e8',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Besøg',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c5453384-2d8f-4b75-b6b0-21b00fe009a4',
    'vocabulary_machine_name' => 'offer_type',
  );
  $terms[] = array(
    'name' => '6 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => 'd0a3b591-cdc7-4238-9d09-1680fe485762',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'HTX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 19,
    'uuid' => 'd2ec93f5-5c98-452c-8420-8873041c9d0e',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Grundskole',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dd78f109-e5ae-43af-80ef-d6a4f5b1029e',
    'vocabulary_machine_name' => 'target_group',
  );
  $terms[] = array(
    'name' => '5 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => 'e09b737c-cb61-4070-acfa-4b109dce6d83',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Natur og friluftsliv',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e7293649-6773-48be-8fb2-293057d1ef0f',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => '9. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 16,
    'uuid' => 'ea8e1b64-6593-4f5e-b2a7-a2546e4125ec',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '4 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => 'eea18b3b-d816-4b4f-b66f-869d112a1019',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '4. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 11,
    'uuid' => 'f507a1f0-cfa6-499d-9a6a-1eca012035fb',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Ungdomsuddannelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ff21ca24-95c3-424d-97b4-0c9e5aed6eb8',
    'vocabulary_machine_name' => 'target_group',
  );
  return $terms;
}
