<?php
/**
 * @file
 * Used to modify different forms on the site.
 */

/**
 * Implements hook_form_alter().
 *
 * Modify forms
 */
function ulf_forms_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
  // Search block.
  case 'search_block_form':
    $form['search_block_form']['#placeholder'] = t('E.g. movie, music etc.');
    $form['search_block_form']['#title'] = FALSE;
    $form['actions']['submit']['#attributes']['class'][] = 'header-search-module--submit';
    break;

  case 'course_node_form':
    $form['#prefix'] = '<div class="node--form is-default-form">';
    $form['#suffix'] = '</div>';
    break;

    case 'course_educators_node_form':
      $form['#prefix'] = '<div class="node--form is-default-form">';
      $form['#suffix'] = '</div>';
      break;

  case 'apachesolr_search_custom_page_search_form':
    $form['#prefix'] = '<div class="search-module"><div class="layout-element-inner"><div class="search-module--form">';
    $form['#suffix'] = '</div></div></div>';
    $form['basic']['submit']['#attributes']['class'][] = 'search-module--submit';
    break;
  }
}
