<?php
/**
 * @file
 * ulf_test_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function ulf_test_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Vikingemuseet under Nordea Bank',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '272ece57-5823-43f2-9622-ce68a7e735a1',
  'type' => 'course',
  'language' => 'da',
  'created' => 1385370578,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '03aaef3b-0f2e-4147-b419-1ae067ebf3ac',
  'revision_uid' => 1,
  'field_count' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_duration' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_duration_unit' => array(
    'und' => array(
      0 => array(
        'value' => 'hours',
      ),
    ),
  ),
  'field_full_description' => array(
    'und' => array(
      0 => array(
        'value' => 'Trappen ned til udstillingen fører os tre meter ned gennem lag af affald fra mange hundrede års byliv. Årstal på trappens trin afspejler rejsen ned gennem jordlagene, tilbage til vikingetiden. Neden for trappens fod står man på samme flade, som vikingerne bebyggede med huse og gader for mere end 1000 år siden.
 
Her genlød det det af travlhed, hønsekaglen, snak og latter inde bag den beskyttende ringvold.
 
Udstillingen tager udgangspunkt i Aros på Harald Blåtands tid, omkring år 980 og viser arkæologiske fund, der kaster lys over byens ældste historie.
 
Vikingemuseet er en del af Moesgård Museum.',
        'format' => NULL,
        'safe_value' => 'Trappen ned til udstillingen fører os tre meter ned gennem lag af affald fra mange hundrede års byliv. Årstal på trappens trin afspejler rejsen ned gennem jordlagene, tilbage til vikingetiden. Neden for trappens fod står man på samme flade, som vikingerne bebyggede med huse og gader for mere end 1000 år siden.
 
Her genlød det det af travlhed, hønsekaglen, snak og latter inde bag den beskyttende ringvold.
 
Udstillingen tager udgangspunkt i Aros på Harald Blåtands tid, omkring år 980 og viser arkæologiske fund, der kaster lys over byens ældste historie.
 
Vikingemuseet er en del af Moesgård Museum.',
      ),
    ),
  ),
  'field_image' => array(
    'und' => array(
      0 => array(
        'fid' => 4,
        'alt' => '',
        'title' => '',
        'width' => 438,
        'height' => 187,
        'uid' => 1,
        'filename' => 'vikingemuseet-438x187.jpg',
        'uri' => 'public://provider_images/vikingemuseet-438x187.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 62266,
        'status' => 1,
        'timestamp' => 1385370578,
        'uuid' => 'a1353846-52a4-47e9-9a87-eeff15a68968',
      ),
    ),
  ),
  'field_price_info' => array(),
  'field_short_description' => array(
    'und' => array(
      0 => array(
        'value' => 'Trappen ned til udstillingen fører os tre meter ned gennem lag af affald fra mange hundrede års byliv. Årstal på trappens trin afspejler rejsen ned gennem jordlagene, tilbage til vikingetiden. Neden for trappens fod står man på samme flade, som vikingerne bebyggede med huse og gader for mere end 1000 år siden.',
        'format' => NULL,
        'safe_value' => 'Trappen ned til udstillingen fører os tre meter ned gennem lag af affald fra mange hundrede års byliv. Årstal på trappens trin afspejler rejsen ned gennem jordlagene, tilbage til vikingetiden. Neden for trappens fod står man på samme flade, som vikingerne bebyggede med huse og gader for mere end 1000 år siden.',
      ),
    ),
  ),
  'field_subject' => array(
    'und' => array(
      0 => array(
        'tid' => 11,
      ),
    ),
  ),
  'field_tags' => array(),
  'field_target_group' => array(
    'und' => array(
      0 => array(
        'tid' => 34,
      ),
    ),
  ),
  'field_target_group_sub' => array(
    'und' => array(
      0 => array(
        'tid' => 4,
      ),
      1 => array(
        'tid' => 25,
      ),
      2 => array(
        'tid' => 5,
      ),
      3 => array(
        'tid' => 10,
      ),
      4 => array(
        'tid' => 39,
      ),
      5 => array(
        'tid' => 26,
      ),
      6 => array(
        'tid' => 12,
      ),
      7 => array(
        'tid' => 29,
      ),
      8 => array(
        'tid' => 28,
      ),
      9 => array(
        'tid' => 37,
      ),
      10 => array(
        'tid' => 13,
      ),
    ),
  ),
  'field_teaser' => array(
    'und' => array(
      0 => array(
        'value' => 'Vikingemuseet under Nordea Bank viser et glimt af vikingebyen Aros bag voldene - baseret på de faktiske udgravninger på netop det sted, hvor udstillingen er bygget op.',
        'format' => NULL,
        'safe_value' => 'Vikingemuseet under Nordea Bank viser et glimt af vikingebyen Aros bag voldene - baseret på de faktiske udgravninger på netop det sted, hvor udstillingen er bygget op.',
      ),
    ),
  ),
  'field_tilbudstype' => array(
    'und' => array(
      0 => array(
        'tid' => 30,
      ),
    ),
  ),
  'field_collection_price' => array(
    'und' => array(
      0 => array(
        'value' => 4,
        'revision_id' => 4,
      ),
    ),
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-11-25 10:09:38 +0100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Rejsen til solen, månen og stjernerne',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '184af912-4ade-4e34-a1ad-cd0b360e3060',
  'type' => 'course',
  'language' => 'da',
  'created' => 1385370007,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '338b8a2d-e47f-4740-a906-3fac4551b853',
  'revision_uid' => 1,
  'field_count' => array(
    'und' => array(
      0 => array(
        'value' => 25,
      ),
    ),
  ),
  'field_duration' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_duration_unit' => array(
    'und' => array(
      0 => array(
        'value' => 'lessons',
      ),
    ),
  ),
  'field_full_description' => array(
    'und' => array(
      0 => array(
        'value' => 'Døren går op og børnene inviteres ind i et rum af fortælling, musik og billeder efter klassisk japansk kamishibai-tradition.
Myter og fortællinger fra hele verden om solen, månen og stjernerne præsenteres i en poetisk, legende og aktivt inddragende form. 
Workshopforestillingen kan spilles enten på skolen eller på Den Jyske Opera efter nærmere aftale og kan efterfølgende naturligt inddrages i både dansk, billedkunst og musikundervisningen.',
        'format' => NULL,
        'safe_value' => 'Døren går op og børnene inviteres ind i et rum af fortælling, musik og billeder efter klassisk japansk kamishibai-tradition.
Myter og fortællinger fra hele verden om solen, månen og stjernerne præsenteres i en poetisk, legende og aktivt inddragende form. 
Workshopforestillingen kan spilles enten på skolen eller på Den Jyske Opera efter nærmere aftale og kan efterfølgende naturligt inddrages i både dansk, billedkunst og musikundervisningen.',
      ),
    ),
  ),
  'field_image' => array(
    'und' => array(
      0 => array(
        'fid' => 2,
        'alt' => '',
        'title' => '',
        'width' => 438,
        'height' => 187,
        'uid' => 1,
        'filename' => 'rejsen-til-solen-maanen-og-stjernerne-438x187.jpg',
        'uri' => 'public://provider_images/rejsen-til-solen-maanen-og-stjernerne-438x187.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 53679,
        'status' => 1,
        'timestamp' => 1385370007,
        'uuid' => 'd7596239-0578-4a39-ba04-de6deaba46f9',
      ),
    ),
  ),
  'field_price_info' => array(
    'und' => array(
      0 => array(
        'value' => 'Refusionsberettiget som børneteater',
        'format' => NULL,
        'safe_value' => 'Refusionsberettiget som børneteater',
      ),
    ),
  ),
  'field_short_description' => array(
    'und' => array(
      0 => array(
        'value' => 'Døren går op og børnene inviteres ind i et rum af fortælling, musik og billeder efter klassisk japansk kamishibai-tradition.
Myter og fortællinger fra hele verden om solen, månen og stjernerne præsenteres i en poetisk, legende og aktivt inddragende form. ',
        'format' => NULL,
        'safe_value' => 'Døren går op og børnene inviteres ind i et rum af fortælling, musik og billeder efter klassisk japansk kamishibai-tradition.
Myter og fortællinger fra hele verden om solen, månen og stjernerne præsenteres i en poetisk, legende og aktivt inddragende form. ',
      ),
    ),
  ),
  'field_subject' => array(
    'und' => array(
      0 => array(
        'tid' => 27,
      ),
    ),
  ),
  'field_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 42,
      ),
    ),
  ),
  'field_target_group' => array(
    'und' => array(
      0 => array(
        'tid' => 34,
      ),
    ),
  ),
  'field_target_group_sub' => array(
    'und' => array(
      0 => array(
        'tid' => 4,
      ),
      1 => array(
        'tid' => 25,
      ),
    ),
  ),
  'field_teaser' => array(
    'und' => array(
      0 => array(
        'value' => 'Døren går op og børnene inviteres ind i et rum af fortælling, musik og billeder efter klassisk japansk kamishibai-tradition.',
        'format' => NULL,
        'safe_value' => 'Døren går op og børnene inviteres ind i et rum af fortælling, musik og billeder efter klassisk japansk kamishibai-tradition.',
      ),
    ),
  ),
  'field_tilbudstype' => array(
    'und' => array(
      0 => array(
        'tid' => 19,
      ),
    ),
  ),
  'field_collection_price' => array(
    'und' => array(
      0 => array(
        'value' => 2,
        'revision_id' => 2,
      ),
    ),
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-11-25 10:00:07 +0100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Lejrskolen i Sahl',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'c0cca4d5-3e37-4c31-b5aa-152828071ace',
  'type' => 'course',
  'language' => 'da',
  'created' => 1385370412,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'bd121746-22e5-4bc3-b013-4806683496f9',
  'revision_uid' => 1,
  'field_count' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_duration' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_duration_unit' => array(
    'und' => array(
      0 => array(
        'value' => 'hours',
      ),
    ),
  ),
  'field_full_description' => array(
    'und' => array(
      0 => array(
        'value' => 'Lejrskolen er udstyret med cykler i klassesæt, så der er gode muligheder for at cykle ud på heden, besøge Hjerl Hedes Frilandsmuseum, kirken, Stubber Kloster eller fiske i gadekæret. Der er plads til 48 børn og deres ledere. Ophold er altid med forplejning. Der er køkken, spisesal, undervisningslokaler inde, og tarzanbane, boldbane, shelters mv. udenfor. ',
        'format' => NULL,
        'safe_value' => 'Lejrskolen er udstyret med cykler i klassesæt, så der er gode muligheder for at cykle ud på heden, besøge Hjerl Hedes Frilandsmuseum, kirken, Stubber Kloster eller fiske i gadekæret. Der er plads til 48 børn og deres ledere. Ophold er altid med forplejning. Der er køkken, spisesal, undervisningslokaler inde, og tarzanbane, boldbane, shelters mv. udenfor. ',
      ),
    ),
  ),
  'field_image' => array(
    'und' => array(
      0 => array(
        'fid' => 3,
        'alt' => '',
        'title' => '',
        'width' => 438,
        'height' => 187,
        'uid' => 1,
        'filename' => 'lejrskolen-i-sahl-438x187.jpg',
        'uri' => 'public://provider_images/lejrskolen-i-sahl-438x187.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 27465,
        'status' => 1,
        'timestamp' => 1385370412,
        'uuid' => '80727f25-f924-4041-93f5-9246fbb88166',
      ),
    ),
  ),
  'field_price_info' => array(),
  'field_short_description' => array(
    'und' => array(
      0 => array(
        'value' => 'Lejrskolen er udstyret med cykler i klassesæt, så der er gode muligheder for at cykle ud på heden, besøge Hjerl Hedes Frilandsmuseum, kirken, Stubber Kloster eller fiske i gadekæret. Der er plads til 48 børn og deres ledere. Ophold er altid med forplejning. Der er køkken, spisesal, undervisningslokaler inde, og tarzanbane, boldbane, shelters mv. udenfor. ',
        'format' => NULL,
        'safe_value' => 'Lejrskolen er udstyret med cykler i klassesæt, så der er gode muligheder for at cykle ud på heden, besøge Hjerl Hedes Frilandsmuseum, kirken, Stubber Kloster eller fiske i gadekæret. Der er plads til 48 børn og deres ledere. Ophold er altid med forplejning. Der er køkken, spisesal, undervisningslokaler inde, og tarzanbane, boldbane, shelters mv. udenfor. ',
      ),
    ),
  ),
  'field_subject' => array(
    'und' => array(
      0 => array(
        'tid' => 36,
      ),
    ),
  ),
  'field_tags' => array(),
  'field_target_group' => array(
    'und' => array(
      0 => array(
        'tid' => 34,
      ),
    ),
  ),
  'field_target_group_sub' => array(
    'und' => array(
      0 => array(
        'tid' => 4,
      ),
      1 => array(
        'tid' => 25,
      ),
      2 => array(
        'tid' => 5,
      ),
      3 => array(
        'tid' => 10,
      ),
      4 => array(
        'tid' => 39,
      ),
      5 => array(
        'tid' => 26,
      ),
      6 => array(
        'tid' => 12,
      ),
      7 => array(
        'tid' => 29,
      ),
      8 => array(
        'tid' => 28,
      ),
      9 => array(
        'tid' => 37,
      ),
      10 => array(
        'tid' => 13,
      ),
    ),
  ),
  'field_teaser' => array(
    'und' => array(
      0 => array(
        'value' => 'Lejrskolen er indrettet i den gamle skole i Sahl nær Vinderup.',
        'format' => NULL,
        'safe_value' => 'Lejrskolen er indrettet i den gamle skole i Sahl nær Vinderup.',
      ),
    ),
  ),
  'field_tilbudstype' => array(
    'und' => array(
      0 => array(
        'tid' => 30,
      ),
    ),
  ),
  'field_collection_price' => array(
    'und' => array(
      0 => array(
        'value' => 3,
        'revision_id' => 3,
      ),
    ),
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-11-25 10:06:52 +0100',
);
  return $nodes;
}
