<?php
/**
 * @file
 * ulf_solr_setup.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function ulf_solr_setup_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "apachesolr" && $api == "apachesolr_environments") {
    return array("version" => "1");
  }
  if ($module == "facetapi" && $api == "facetapi_defaults") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
