<?php

/**
 * @file Secure Permissions Data
 * Module file for secure permissions in code.
 */

/**
 * Define site roles in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @return
 *   An array defining all the roles for the site.
 */
function secure_permissions_data_secure_permissions_roles() {
  return array(
    'anonymous user',
    'authenticated user',
    'course provider',
    'editor',
  );
}

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */
function secure_permissions_data_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'access content',
      'access PDF version',
      'access user profiles',
      'display EU Cookie Compliance popup',
      'search content',
      'use manualcrop',
      'view node map',
      'view user map',
    ),
    'authenticated user' => array(
      'access content',
      'access PDF version',
      'access user profiles',
      'display EU Cookie Compliance popup',
      'edit mimemail user settings',
      'search content',
      'use manualcrop',
      'view node map',
      'view user map',
    ),
    'course provider' => array(
      'access contextual links',
      'access toolbar',
      'access workbench',
      'administer user locations',
      'change own username',
      'clone node',
      'create course content',
      'create course_educators content',
      'edit own course content',
      'edit own course_educators content',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to draft',
      'schedule publishing of nodes',
      'submit latitude/longitude',
      'switch shortcut sets',
      'use text format editor',
      'use workbench_moderation my drafts tab',
      'view all user locations',
      'view moderation history',
      'view node map',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
      'view user map',
    ),
    'editor' => array(
      'access administration pages',
      'access broken links report',
      'access content overview',
      'access contextual links',
      'access own broken links report',
      'access site reports',
      'access toolbar',
      'access user profiles',
      'access workbench',
      'administer blocks',
      'administer custom content',
      'administer EU Cookie Compliance popup',
      'administer mail templates',
      'administer mailchimp',
      'administer menu',
      'administer nodequeue',
      'administer nodes',
      'administer path metatags',
      'administer permissions',
      'administer taxonomy',
      'administer url aliases',
      'administer user locations',
      'administer users',
      'administer workbench moderation',
      'block IP addresses',
      'bypass workbench moderation',
      'change own username',
      'clone node',
      'create course content',
      'create course_educators content',
      'create html_block content',
      'create news content',
      'create static_page content',
      'create url aliases',
      'delete any html_block content',
      'delete any news content',
      'delete any static_page content',
      'delete own html_block content',
      'delete own news content',
      'delete own static_page content',
      'delete revisions',
      'edit any course content',
      'edit any course_educators content',
      'edit any html_block content',
      'edit any news content',
      'edit any static_page content',
      'edit own course content',
      'edit own course_educators content',
      'edit own html_block content',
      'edit own news content',
      'edit own static_page content',
      'manipulate all queues',
      'manipulate queues',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to draft',
      'moderate content from needs_review to published',
      'revert revisions',
      'set own user location',
      'submit latitude/longitude',
      'switch shortcut sets',
      'translate interface',
      'use panels dashboard',
      'use panels in place editing',
      'use ipe with page manager',
      'use text format editor',
      'use text format full_html',
      'use workbench_moderation my drafts tab',
      'use workbench_moderation needs review tab',
      'view all unpublished content',
      'view all user locations',
      'view moderation history',
      'view node map',
      'view own unpublished content',
      'view own user location',
      'view pane admin links',
      'view revisions',
      'view the administration theme',
      'view user map',
      'schedule publishing of nodes',
      'view scheduled content',
      'view_blocked_users',
      'administer custom settings',
      'add better descriptions to fields',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
