<?php

/**
 * @file Secure Permissions Data
 * Module file for secure permissions in code.
 */

/**
 * Define site roles in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @return array
 *   An array defining all the roles for the site.
 */
function secure_permissions_data_secure_permissions_roles() {
  return array(
    'anonymous user',
    'authenticated user',
    'course provider',
    'editor',
  );
}

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return array
 *   An array defining all the permissions for the site.
 */
function secure_permissions_data_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'access content',
      'access PDF version',
      'access user profiles',
      'use manualcrop',
    ),
    'authenticated user' => array(
      'access content',
      'access PDF version',
      'access user profiles',
      'edit mimemail user settings',
      'use manualcrop',
    ),
    'course provider' => array(
      'access contextual links',
      'access toolbar',
      'access workbench',
      'change own username',
      'create course content',
      'create course_educators content',
      'delete own course content',
      'delete own course_educators content',
      'edit own course content',
      'edit own course_educators content',
      'moderate content from draft to needs_review',
      'switch shortcut sets',
      'use text format editor',
      'use workbench_moderation my drafts tab',
      'view moderation history',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
    ),
    'editor' => array(
      'access administration pages',
      'access broken links report',
      'access content overview',
      'access contextual links',
      'access own broken links report',
      'access site reports',
      'access toolbar',
      'access user profiles',
      'access workbench',
      'administer blocks',
      'administer custom content',
      'administer mail templates',
      'administer menu',
      'administer nodes',
      'administer path metatags',
      'administer permissions',
      'administer taxonomy',
      'administer url aliases',
      'administer users',
      'administer workbench moderation',
      'block IP addresses',
      'change own username',
      'clone node',
      'create course content',
      'create course_educators content',
      'create news content',
      'create static_page content',
      'create url aliases',
      'delete any course content',
      'delete any course_educators content',
      'delete any news content',
      'delete any static_page content',
      'delete own course content',
      'delete own course_educators content',
      'delete own news content',
      'delete own static_page content',
      'delete revisions',
      'edit any course content',
      'edit any course_educators content',
      'edit any news content',
      'edit any static_page content',
      'edit own course content',
      'edit own course_educators content',
      'edit own news content',
      'edit own static_page content',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to published',
      'revert revisions',
      'switch shortcut sets',
      'translate interface',
      'use panels dashboard',
      'use text format editor',
      'use text format full_html',
      'use workbench_moderation my drafts tab',
      'use workbench_moderation needs review tab',
      'view all unpublished content',
      'view moderation history',
      'view own unpublished content',
      'view pane admin links',
      'view revisions',
      'view the administration theme',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}