<?php
/**
 * @file
 * ulf_taxonomy_terms.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function ulf_taxonomy_terms_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Erhvervsøkonomi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 17,
    'uuid' => '00d2988b-7e3f-4896-aa68-aeea2281df93',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'International teknologi og kultur',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 29,
    'uuid' => '01a57ce1-eaea-4df9-9614-988a0942158d',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Børnehave',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '02b3b934-2e84-49cd-b376-c6da36826d6b',
    'vocabulary_machine_name' => 'course_relevancy_educators',
  );
  $terms[] = array(
    'name' => 'Sløjd',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 18,
    'uuid' => '05d9ed85-9663-4cd1-9533-f79910bc7eb5',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Arabisk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => '07157462-a123-4869-865c-ac8a1f3e20a0',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Håndarbejde',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '0a889e2b-07c7-4a3a-9e89-40a4ee939194',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Kulturelle udtryksformer og værdier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '0ed4d5f6-bf37-4bef-8b93-710edebe0056',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Almen studieforberedelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '0f1faddd-2a1d-4e12-ae44-bc83dc1af7b0',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'HHX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 20,
    'uuid' => '10bc7b6e-29b3-4a58-b948-7475a89670eb',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Mediefag (film og tv)',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 43,
    'uuid' => '14f0f7f3-48d3-4051-913c-bb562f52087f',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Dagtilbud',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '18824c90-f2f0-4734-9310-ed4ae77243ae',
    'vocabulary_machine_name' => 'target_group',
  );
  $terms[] = array(
    'name' => '0. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => '1b3edbc3-53cc-4fd0-bfba-6e4de193d8ed',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Alsidig personlig udvikling',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '1e0b4031-423d-48aa-b861-18ad4edabbdb',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => '2. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '1e1b9107-5755-47c4-8d8d-09f75a5dcf28',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Materialeteknologi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 42,
    'uuid' => '1ed3f852-5148-413c-a305-cca18e27a17e',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Matematik',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 41,
    'uuid' => '1f553ff2-0a4d-4239-925e-e13c1457a737',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '0 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '25a5e454-f086-45b5-a122-1fea816d31ed',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Dramatik',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 14,
    'uuid' => '25a9a335-64e5-4b2f-b73d-e9776b138e53',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Japansk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 33,
    'uuid' => '268a091d-f812-49b9-b1db-06c49ec660cb',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'HF',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 21,
    'uuid' => '26aed059-b358-47df-a8a9-f755671e5853',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => '3 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '26e1ac50-e997-400e-8ca5-c0dd88d6de21',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Drama',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => '295d994f-0ca7-437e-af13-74e0b861ea40',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Afsætning',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '2aababfb-d5a7-49f9-822f-02efd3db3d3c',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Vuggestue',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '339a847d-9744-4cd8-b3b4-fafbc283346c',
    'vocabulary_machine_name' => 'course_relevancy_educators',
  );
  $terms[] = array(
    'name' => 'Kinesisk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 35,
    'uuid' => '365b1226-fdb0-4466-a23a-29962369d674',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'SFO',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '368efe23-0e3d-46e0-be66-2811b464f2ac',
    'vocabulary_machine_name' => 'course_relevancy_educators',
  );
  $terms[] = array(
    'name' => 'Engelsk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 15,
    'uuid' => '3b2b9f09-c0aa-41ce-9d68-98e98382db95',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Billedkunst',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '3d0879aa-0e0b-40c9-85b1-aba7c890140d',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => '1 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '3d7dfa93-ef8d-4e60-9bb5-9407cb9133c4',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kultur- og samfundsfaggruppen',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 37,
    'uuid' => '41f94282-eff4-4667-ba1f-eb6a61c0a653',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Ungdomsskole',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => '43642c4a-7f0b-4721-87cb-35cc500c5b99',
    'vocabulary_machine_name' => 'course_relevancy_educators',
  );
  $terms[] = array(
    'name' => 'Studieretningsprojektet',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 62,
    'uuid' => '46462e02-04c9-4b80-83e1-c1fe21313207',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Latin',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 39,
    'uuid' => '46797d54-33f2-4625-a028-80da8adab981',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Virksomhedsøkonomi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 68,
    'uuid' => '469efe7e-9e53-408a-af29-2a6bf9495af1',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Ungdomsuddannelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '488e4730-bdce-49fa-8af8-fce763b546b4',
    'vocabulary_machine_name' => 'course_relevancy_educators',
  );
  $terms[] = array(
    'name' => '3. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 10,
    'uuid' => '4941e01e-9dc0-4e83-a147-a51e9fbfe5c6',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kulturhistorie og kulturarv',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4b2fd2d2-eb1d-49dc-b133-347aafd3021d',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Fransk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => '4e29947d-d96f-46b7-b8cc-77e4065929ac',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Informationsteknologi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 27,
    'uuid' => '4eff12cf-ff4d-434d-9de8-09a9644bb394',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'International økonomi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 30,
    'uuid' => '5149a8c8-2a2a-476a-9b93-7219ee8beec8',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '6. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 13,
    'uuid' => '540acde5-2d57-4eab-b44d-9150233c1be2',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Dans',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '57e16aec-9676-4c39-bccf-1cba4656384a',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Historie',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 24,
    'uuid' => '58a46aa4-156e-4f88-957c-e2cb43149d55',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '10. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 17,
    'uuid' => '59b279fe-6430-4895-896e-ae0e931ee9f2',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Klub',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => '5b0e4059-e643-48df-8e8f-62253bd58cba',
    'vocabulary_machine_name' => 'course_relevancy_educators',
  );
  $terms[] = array(
    'name' => 'Sproglig udvikling',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => '5b8a0bda-fab5-41df-963c-e2283d7b5305',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'STX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 18,
    'uuid' => '5c79aa0c-dc12-4eba-b9a4-b1ee9d779d86',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Naturgeografi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 46,
    'uuid' => '5e10767c-01eb-424b-a303-9c75d124b297',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Studieområdet',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 61,
    'uuid' => '6243aaa0-8118-4415-b477-e6f49f493224',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Spansk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 58,
    'uuid' => '62c87a82-e6a4-49e6-a8e0-3067656f4f96',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Erhvervsret',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 16,
    'uuid' => '638d1de4-c2a9-4a31-967a-ebe6b988471d',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '2 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '65d2a9c0-57f3-43f8-8cb5-cf2ee04611a9',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Design',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 13,
    'uuid' => '67c31e98-f36f-4aeb-ab4e-b21cdf3a1b7a',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Idræt',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 12,
    'uuid' => '6817eca7-d6ef-4a31-b51a-ddf10cef8055',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Programmering',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 51,
    'uuid' => '689d0a4a-7cdf-4d5d-97a0-3e2fa90da560',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Tyrkisk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 66,
    'uuid' => '6a66fbae-ee6a-40e7-8866-ecb5851ae6bd',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Kunst, arkitektur og design',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6d486dc2-d02f-4fe2-a0c0-08659ac5fa36',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Almen sprogforståelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '6dbb8d83-ee38-4c9b-a914-4ea4020b2dba',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Forløb',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6ddf328e-e644-47ba-b94c-40b1c1c7bf02',
    'vocabulary_machine_name' => 'offer_type',
  );
  $terms[] = array(
    'name' => 'Historie',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 10,
    'uuid' => '711c1e52-6471-42fa-abae-0671630cd21d',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Mellemtrin',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => '72bf19de-2695-4480-83da-3a884045e902',
    'vocabulary_machine_name' => 'course_relevancy_educators',
  );
  $terms[] = array(
    'name' => 'Markedskommunikation',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 40,
    'uuid' => '73132128-5b40-4faa-a4bf-72574e544f85',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Idehistorie',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 25,
    'uuid' => '7458d3fd-53bf-4027-a8a9-d2bfb37f0d24',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Naturvidenskabelig faggruppe',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 47,
    'uuid' => '77c2650a-aea8-452f-b34b-5e200c4a365d',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Engelsk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => '78576146-62b2-495c-a4d1-727c7c129f5b',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Kommunikation/it',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 36,
    'uuid' => '78b7a199-0cd5-40b0-a0a9-ef3623231663',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Samtidshistorie',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 57,
    'uuid' => '7c239fb3-5b4a-4e46-bd65-461b41b23b56',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Tysk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 19,
    'uuid' => '7ddfc0b0-143b-4fed-94fb-24b56f5edc69',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Tværfaglige tilbud',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8002d3cc-f51a-4895-a08a-ffb18166fbc9',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Billedkunst',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => '8147cdbb-0ded-4c70-8866-b783f61cfced',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Krop og bevægelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '821ac08b-3627-4138-b232-b8946da419a0',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Idræt og bevægelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8631fc63-25c3-41d8-a945-392602ab8d50',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Fysik',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 21,
    'uuid' => '8b38d992-8c90-4895-bc30-3de57255a2c4',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Teknikfag',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 63,
    'uuid' => '8b774418-2218-4bc0-907c-b6f9473c6501',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Naturvidenskab',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8f029972-cf4b-4d60-8b4b-bd40335cf4bb',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Bioteknologi (forsøg)',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => '927a82db-870a-4f9b-b708-387eb3fd94ed',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Statistik',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 60,
    'uuid' => '94cbfc87-6d1d-40f1-8400-552632855441',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Astronomi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => '95b02331-3e64-49d7-9956-5f54dcb9d5b1',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '1. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => '95bc7a90-bfd1-4ac4-b00e-3edbf958fe69',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Geografi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => '9bd79136-2d6e-4511-848b-623ee30978e3',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Biologi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '9d10bf72-12a1-4554-840d-5d013c7121e6',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Matematik',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 14,
    'uuid' => 'a0c6ed72-a901-4cc0-85ea-1af7d441c140',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Russisk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 55,
    'uuid' => 'a0fd2605-6e72-4977-b087-359bc11e094a',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Organisation',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 50,
    'uuid' => 'a1305063-f0f7-40e2-b573-cb43ee600088',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Natur og naturfænomener',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => 'a35150d9-998a-4b6c-b95a-6d3169ef64be',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Dansk som andetsprog (forsøg)',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 11,
    'uuid' => 'a5238510-fc16-436a-862d-40abab74917e',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '5. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 12,
    'uuid' => 'a69b46be-77eb-4fdf-bcc4-b65ab163f5ce',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Religion',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 53,
    'uuid' => 'a97f7bc3-b5b8-4e1c-b00f-d766ff51f034',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Film, musik, teater og dans',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ab70ca4c-35b3-4714-85be-23dee6ad4ad0',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Dansk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => 'ad542e3b-4755-435c-b061-df0c4f743922',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Datalogi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 12,
    'uuid' => 'b1a09677-faae-4f87-b93e-ad92918d4f53',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Kemi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 34,
    'uuid' => 'b2d51035-ee98-4956-841d-6f586208e755',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '8. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 15,
    'uuid' => 'b4b966b5-7404-4c51-b38d-738f16649e8b',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kristendom',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 13,
    'uuid' => 'b81c39eb-e67b-4176-bf18-a2e0020bc101',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Geografi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 22,
    'uuid' => 'b9aae0ad-3b04-4318-b768-c2b4d7adc72c',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Multimedier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 44,
    'uuid' => 'b9b4dce6-b9a0-4eb9-b1ff-5ef6eab58078',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '7. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 14,
    'uuid' => 'bd6809f5-5e83-4bcd-87b4-e2ee84a615e8',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Oldtidskundskab',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 49,
    'uuid' => 'c168f678-50a9-4194-b6c7-c012d7f6f03d',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Finansiering',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 19,
    'uuid' => 'c185c015-f367-479d-a9d8-6b594587d0ad',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Naturvidenskabeligt grundforløb',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 48,
    'uuid' => 'c273771e-e208-4a3b-bfe5-1a6ade85c46c',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Samfundsfag',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 56,
    'uuid' => 'c4d3a443-e2da-4272-9302-d09a69d8f31c',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Besøg',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c5453384-2d8f-4b75-b6b0-21b00fe009a4',
    'vocabulary_machine_name' => 'offer_type',
  );
  $terms[] = array(
    'name' => 'Sociale kompetencer',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => 'c6c204f5-121f-4bb0-8900-37f29ff69211',
    'vocabulary_machine_name' => 'educational_goals',
  );
  $terms[] = array(
    'name' => 'Græsk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 23,
    'uuid' => 'c7c107d3-4fc7-471a-965b-6d74b141dab7',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Retorik',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 54,
    'uuid' => 'c880e4dc-2773-49b6-8ce3-187f296adece',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Teknologihistorie',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 65,
    'uuid' => 'ca170e1b-bc9b-43a5-8513-92e2dfb72f47',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Samfundsfag',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 17,
    'uuid' => 'cc70bde5-77d4-4277-a5e2-46299543fd7c',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Hjemkundskab',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 11,
    'uuid' => 'cd3657b9-8a27-434b-82b8-bc339e51775c',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => '6 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => 'd0a3b591-cdc7-4238-9d09-1680fe485762',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Fysik/kemi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => 'd1479a93-2243-4915-a74d-c4f57a148676',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Teknologi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 64,
    'uuid' => 'd155a674-83ad-4e90-b4f9-da2df6b95ec2',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'HTX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 19,
    'uuid' => 'd2ec93f5-5c98-452c-8420-8873041c9d0e',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Psykologi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 52,
    'uuid' => 'd804e279-6d4c-4de2-983a-5524f2b847e0',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Tysk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 67,
    'uuid' => 'd82b8bb4-6449-494d-b005-4544cfcd0bbf',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Innovation',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 28,
    'uuid' => 'd8c2e475-67f7-4354-9f86-d95dfc45287d',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'It',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 31,
    'uuid' => 'd953de7c-5f53-4bee-9f00-25fa310f21f9',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Grundskole',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dd78f109-e5ae-43af-80ef-d6a4f5b1029e',
    'vocabulary_machine_name' => 'target_group',
  );
  $terms[] = array(
    'name' => 'Idræt',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 26,
    'uuid' => 'e061ca2b-a628-46ca-b6b5-3873d6d04fe6',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '5 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => 'e09b737c-cb61-4070-acfa-4b109dce6d83',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Kulturforståelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 38,
    'uuid' => 'e4ba6836-9455-41c8-bee5-6212f8808239',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Filosofi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 18,
    'uuid' => 'e654d5da-8323-4bb6-81a9-bc2a92fa4c14',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Natur og friluftsliv',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e7293649-6773-48be-8fb2-293057d1ef0f',
    'vocabulary_machine_name' => 'topic',
  );
  $terms[] = array(
    'name' => 'Musik',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 15,
    'uuid' => 'e785a18e-941e-4642-a9b6-c53ec555805b',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => '9. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 16,
    'uuid' => 'ea8e1b64-6593-4f5e-b2a7-a2546e4125ec',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Indskoling',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => 'eb4e89c9-5fc7-4a0b-92ef-c7003fca4759',
    'vocabulary_machine_name' => 'course_relevancy_educators',
  );
  $terms[] = array(
    'name' => 'Dansk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 10,
    'uuid' => 'ebc745d8-d338-46b3-98ec-667ba9eb478e',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Udskoling',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => 'ebdcda5e-738a-45a4-ac6b-26599d0871f2',
    'vocabulary_machine_name' => 'course_relevancy_educators',
  );
  $terms[] = array(
    'name' => '4 år',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => 'eea18b3b-d816-4b4f-b66f-869d112a1019',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Statik og styrkelære',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 59,
    'uuid' => 'ef8518ad-7796-49fa-b5c6-3c172e31a828',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Fransk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 20,
    'uuid' => 'f14cc390-2761-4d01-b787-6bcd59281780',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => '4. klasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 11,
    'uuid' => 'f507a1f0-cfa6-499d-9a6a-1eca012035fb',
    'vocabulary_machine_name' => 'target_group_sub',
  );
  $terms[] = array(
    'name' => 'Italiensk',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 32,
    'uuid' => 'f6108e13-e650-4f3b-b358-a85708f1e187',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Biologi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => 'fae6aa1f-48d2-4126-bb78-7810e8ee936d',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Musik',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 45,
    'uuid' => 'fcc59f4c-3695-4903-9e9e-191821444b54',
    'vocabulary_machine_name' => 'subjects_youth',
  );
  $terms[] = array(
    'name' => 'Natur/teknik',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 16,
    'uuid' => 'fd29c610-341d-4c4e-882e-74ee4644b6d1',
    'vocabulary_machine_name' => 'subjects_primary_school',
  );
  $terms[] = array(
    'name' => 'Ungdomsuddannelse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ff21ca24-95c3-424d-97b4-0c9e5aed6eb8',
    'vocabulary_machine_name' => 'target_group',
  );
  return $terms;
}
