<?php
/**
 * @file
 * Code for the Ulf course providers feature.
 */

include_once 'ulf_course_providers.features.inc';

/**
 * Implements hook_menu_alter()
 *
 * @param $items
 */
function ulf_course_providers_menu_alter(&$items) {
  $items['user/%user']['access callback'] = '_ulf_course_providers_profile_access';
}

/**
 * Implements hook_permission().
 *
 * A permission to view blocked users
 */
function ulf_course_providers_permission() {
  return array(
    'view_blocked_users' => array(
      'title' => t('View blocked users'),
      'description' => t('View blocked users.'),
    ),
  );
}

/**
 * Custom access callback for user profiles.
 *
 * Allow view access to blocked users.
 */
function _ulf_course_providers_profile_access($user) {
  if (user_access('view_blocked_users') || $user->status > 0) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}