<?php
/**
 * @file
 * Code for the Ulf course providers feature.
 */

include_once 'ulf_course_providers.features.inc';

/**
 * Implements hook_menu_alter()
 *
 * @param $items
 */
function ulf_course_providers_menu_alter(&$items) {
  $items['user/%user']['access callback'] = '_ulf_course_providers_profile_access';
}

/**
 * Custom access callback for user profiles.
 *
 * Allow view access to blocked users.
 */
function _ulf_course_providers_profile_access() {
  if (user_access('access content')) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}
