<?php
/**
 * @file
 * Code for the Ulf course providers feature.
 */

include_once 'ulf_course_providers.features.inc';

/**
 * Implements hook_menu_alter()
 *
 * @param $items
 */
function ulf_course_providers_menu_alter(&$items) {
  $items['user/%user/view']['access callback'] = '_ulf_course_providers_profile_access';
}


/**
 * Implements hook_form_FORMID_alter().
 */
function ulf_course_providers_form_user_register_form_alter(&$form, &$form_state) {
  _ulf_course_providers_cleanup_form($form);
}

function ulf_course_providers_form_user_profile_form_alter(&$form, &$form_state) {
  _ulf_course_providers_cleanup_form($form);
}

/**
 * Implements hook_permission().
 *
 * A permission to view blocked users
 */
function ulf_course_providers_permission() {
  return array(
    'view_blocked_users' => array(
      'title' => t('View blocked users'),
      'description' => t('View blocked users.'),
    ),
  );
}

/**
 * Custom access callback for user profiles.
 *
 * Allow view access to blocked users.
 */
function _ulf_course_providers_profile_access() {
  $user = user_load(arg(1));
  if (user_access('view_blocked_users') || $user->status > 0) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Modify the user form.
 *
 * @param $form
 *   The form we modify.
 */
function _ulf_course_providers_cleanup_form(&$form) {
  if (!user_access('administer users')) {
    $form['#fieldgroups']['group_editor_settings']->format_type = 'hidden';
    $form['field_bypass_workflow']['#access'] = FALSE;
    $form['field_editor_info']['#access'] = FALSE;
  }
}