<?php
/**
 * @file
 * ulf_entityform.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function ulf_entityform_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_message_parent_node'.
  $field_bases['field_message_parent_node'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_message_parent_node',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'course' => 'course',
          'course_educators' => 'course_educators',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
