<?php
/**
 * @file
 * Code for the Ulf entityform feature.
 */

include_once 'ulf_entityform.features.inc';
include_once 'ulf_entityform.features.field_base.inc';
include_once 'ulf_entityform.features.field_instance.inc';
if(variable_get('ulf_entityform_enable_editor_forms', false)) {
  include_once 'ulf_entityform.editorforms.inc';
}


function _ulf_entityform_add_node_reference_submit(&$form, &$form_state) {
  if(isset($form['field_message_parent_node'])) {
    $form_state['values']['field_message_parent_node'][LANGUAGE_NONE][0]['target_id'] = $form['#parent_nid'];
  }
  if(isset($form['field_message_parent_node_nomail'])) {
    $form_state['values']['field_message_parent_node_nomail'][LANGUAGE_NONE][0]['target_id'] = $form['#parent_nid'];
  }
}

/**
 * Implements hook_form_alter().
 */
function ulf_entityform_form_alter(&$form, &$form_state, $form_id)
{
  if(strpos($form_id, '_entityform_edit_form') > 0) {
    if(isset($form['field_message_parent_node']) || isset($form['field_message_parent_node_nomail'])) {
      if(isset($form['field_message_parent_node'])) {
        $form['field_message_parent_node']['#access'] = FALSE;
      }
      if(isset($form['field_message_parent_node_nomail'])) {
        $form['field_message_parent_node_nomail']['#access'] = FALSE;
      }
      if (!empty(arg(0)) && arg(0) == 'node') {
        $form['#parent_nid'] = arg(1);
      }
      if (isset($form['actions']['submit'])) {
        if(isset($form['actions']['submit']['#submit']) && is_array($form['actions']['submit']['#submit'])) {
          array_unshift($form['actions']['submit']['#submit'], '_ulf_entityform_add_node_reference_submit');
        } else {
          $form['actions']['submit']['#submit'] = ['_ulf_entityform_add_node_reference_submit'];
        }
      }
    }
    if(isset($form['field_message_recipient_mail'])) {
      $form['field_message_recipient_mail']['#access'] = FALSE;
    }
    if(isset($form['field_message_recipient_provider'])) {
      $form['field_message_recipient_provider']['#access'] = FALSE;
    }
  }

  if(variable_get('ulf_entityform_enable_editor_forms', false)) {
    _ulf_entityform_form_alter($form, $form_state, $form_id);
  }
}

/**
 * Implements hook_entityform_type_insert().
 */
function ulf_entityform_entityform_type_insert($entityform_type) {
  db_insert('captcha_points')
    ->fields(array(
      'form_id' => $entityform_type->type.'_entityform_edit_form',
      'captcha_type' => 'default',
    ))
    ->execute();
}
