<?php
/**
 * @file
 * Code for the Ulf maps feature.
 */

include_once 'ulf_maps.features.inc';

/**
 * Implements hook_form_alter().
 */
function ulf_maps_form_alter(&$form, &$form_state, $form_id) {
  // The form ids of the forms to alter.
  $form_ids = array(
    'user_profile_form',
    'course_node_form',
    'course_educators_node_form',
  );
  if (in_array($form_id, $form_ids)) {
    // If location modules are set up.
    if (isset($form['locations'])) {
      //$mapconfig = variable_get('gmap_default');
      // Attach js to the form.
      $form['#attached']['js'][] = drupal_get_path('module', 'ulf_maps') . '/js/show-map.admin.js';
      array_unshift($form['#submit'], '_ulf_maps_profile_submit');
    }
  }
}


/**
 * Ajax callback that updates the map marker.
 */
function ulf_maps_update_location($form, &$form_state) {
  // Get lat/lon for the address.
  $data = location_latlon_exact($form_state['values']['locations'][0]);

  // Update the values in the form.
  $form['locations'][0]['locpick']['user_latitude']['#value'] = $data['lat'];
  $form['locations'][0]['locpick']['user_longitude']['#value'] = $data['lon'];

  // Update default values with the new values.
  $form['locations'][0]['#default_value']['latitude'] = $data['lat'];
  $form['locations'][0]['#default_value']['longitude'] = $data['lon'];
  $form_state['values']['locations'][0]['locpick']['user_latitude'] = $data['lat'];
  $form_state['values']['locations'][0]['locpick']['user_longitude'] = $data['lon'];

  // Update map information with new location.
  $form['locations'][0]['locpick']['map']['#gmap_settings']['latitude'] = $data['lat'];
  $form['locations'][0]['locpick']['map']['#gmap_settings']['longitude'] = $data['lon'];
  $form['locations'][0]['locpick']['map']['#gmap_settings']['latlong'] = $data['lat'] . ',' . $data['lon'];
  $form['locations'][0]['locpick']['current']['current_latitude']['#markup'] = $data['lat'];
  $form['locations'][0]['locpick']['current']['current_longitude']['#markup'] = $data['lon'];

  // Change clicked button text.
  $form['locations'][0]['submit']['#value'] = t('Reset marker');

  // Class hack to handle JS.
  $form['locations'][0]['#attributes']['class'] = array(
    'location',
    'js-show-map',
  );

  // Render the form and remove messages.
  $element = render($form['locations']);
  drupal_get_messages();

  return $element;
}


/**
 * Ajax callback that resets the map marker and lat/lon.
 */
function ulf_maps_reset_coordinates($form, &$form_state) {
  // Update the values in the form.
  $form['locations'][0]['locpick']['user_latitude']['#value'] = '';
  $form['locations'][0]['locpick']['user_longitude']['#value'] = '';

  // Update default values with the new values.
  $form['locations'][0]['#default_value']['latitude'] = '';
  $form['locations'][0]['#default_value']['longitude'] = '';
  $form_state['values']['locations'][0]['locpick']['user_latitude'] = '';
  $form_state['values']['locations'][0]['locpick']['user_longitude'] = '';

  // Update map information with new location.
  $form['locations'][0]['locpick']['map']['#gmap_settings']['latitude'] = '';
  $form['locations'][0]['locpick']['map']['#gmap_settings']['longitude'] = '';
  $form['locations'][0]['locpick']['map']['#gmap_settings']['latlong'] = '' . ',' . '';
  $form['locations'][0]['locpick']['current']['current_latitude']['#markup'] = '';
  $form['locations'][0]['locpick']['current']['current_longitude']['#markup'] = '';

  // Change clicked button text.
  $form['locations'][0]['submit']['#value'] = t('Specify entrance on map');

  // Class hack to handle JS.
  $form['locations'][0]['#attributes']['class'] = array(
    'location',
    'js-enable-address',
  );

  // Render the from an remove messages.
  $element = render($form['locations']);

  drupal_get_messages();
  return $element;
}

/**
 * Reset location if address depending on value og place_settings selector false
 *
 * @param $form
 * @param $form_state
 */
function _ulf_maps_profile_submit($form, &$form_state) {
  _reset_coordinates($form, $form_state);
}

/**
 * Reset coordinates for the form.
 * @param $form
 * @param $form_state
 */
function _reset_coordinates($form, $form_state) {
  // Update the values in the form.
  $form['locations'][0]['locpick']['user_latitude']['#value'] = '0.000000';
  $form['locations'][0]['locpick']['user_longitude']['#value'] = '0.000000';

  // Update default values with the new values.
  $form['locations'][0]['#default_value']['latitude'] = '0.000000';
  $form['locations'][0]['#default_value']['longitude'] = '0.000000';
  $form_state['values']['locations'][0]['locpick']['user_latitude'] = '0.000000';
  $form_state['values']['locations'][0]['locpick']['user_longitude'] = '0.000000';

  // Update map information with new location.
  $form['locations'][0]['locpick']['map']['#gmap_settings']['latitude'] = '0.000000';
  $form['locations'][0]['locpick']['map']['#gmap_settings']['longitude'] = '0.000000';
  $form['locations'][0]['locpick']['map']['#gmap_settings']['latlong'] = '0.000000' . ',' . '0.000000';
  $form['locations'][0]['locpick']['current']['current_latitude']['#markup'] = '0.000000';
  $form['locations'][0]['locpick']['current']['current_longitude']['#markup'] = '0.000000';
}