<div class="block-inline-module">
  <h2 class="block-inline-module--header">Nyttigt</h2>
  <div class="block-inline-module--content contextual-links-region">
    <ul class="block--list">
      <li class="block--list-item">Mulighed for at spise medbragt mad</li>
      <li class="block--list-item">Mulighed for toiletbesøg</li>
      <li class="block--list-item">Handicapvenlige forhold</li>
    </ul>
  </div>
</div>
