<div class="block-inline-module">
  <h2 class="block-inline-module--header">Practical information</h2>
  <div class="block-inline-module--content contextual-links-region">
    <div class="block-inline-module--field-wrapper">
      <div class="block-inline-module--field-label">Emneområde</div>
      <div class="block-inline-module--field-text">
        <a href="/forloeb/kulturhistorie-og-kulturarv">Kulturhistorie og kulturarv</a>
      </div>
      <div class="block-inline-module--field-label">Tilbudstype</div>
      <div class="block-inline-module--field-text">
        <a href="/forloeb/forl%C3%B8b">Forløb</a>
      </div>
    </div>
    <div class="block-inline-module--field-wrapper">
      <div class="block-inline-module--field-label">Antal deltagere</div><div class="block-inline-module--field-text">23</div>
      <div class="block-inline-module--field-label">Målgruppe</div><div class="block-inline-module--field-text"><a href="/forloeb/1-%C3%A5r">1 år</a>, <a href="/forloeb/2-%C3%A5r">2 år</a>, <a href="/forloeb/3-%C3%A5r">3 år</a></div>
    </div>
    <div class="block-inline-module--field-wrapper">
      <div class="block-inline-module--field-label">Varighed</div>
      <div class="block-inline-module--field-text">32 Lektioner</div>
      <div class="block-inline-module--field-label">Pris</div>
      <div class="block-inline-module--field-text">
        <div class="field-collection-module--value">
          <span class="field-collection-module--price">2323,-</span>
          <span class="field-collection-module--unit-price">pr. elev/barn/person</span>
        </div>
        <div class="field-collection-module--value">
          <span class="field-collection-module--price">2323,-</span>
          <span class="field-collection-module--unit-price">pr. elev/barn/person</span>
        </div>
        <div class="field-collection-module--value">
          <span class="field-collection-module--price">111,-</span>
          <span class="field-collection-module--unit-price">pr. gruppe</span>
        </div>
      </div>
    </div>
    <div class="block-module--field-wrapper">
      <div class="block-module--field-label">Yderligere information</div><div class="block-inline-module--field-text">sdsada</div>
    </div>
  </div>
</div>