<div class="block-module">
  <h2 class="block-module--header">Nyheder</h2>
  <div class="block-module--content contextual-links-region">
    <div class="block-module--content-element-wrapper">
      <h3 class="block-module--content-label">
        <a href="#">Lorem ipsum lige her</a>
        </h2>
        <div class="block-module--content-element">
          THis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsum.
        </div>
        <a href="#">Læs nyheden</a>
    </div>
    <div class="block-module--content-element-wrapper">
      <h3 class="block-module--content-label">
        <a href="#">Lorem ipsum lige her</a>
        </h2>
        <div class="block-module--content-element">
          THis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsum.
        </div>
        <a href="#">Læs nyheden</a>
    </div>
    <div class="block-module--content-element-wrapper">
      <h3 class="block-module--content-label">
        <a href="#">Lorem ipsum lige her</a>
        </h2>
        <div class="block-module--content-element">
          THis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsum.
        </div>
        <a href="#">Læs nyheden</a>
    </div>
    <div class="block-module--content-element-wrapper">
      <h3 class="block-module--content-label">
        <a href="#">Lorem ipsum lige her</a>
        </h2>
        <div class="block-module--content-element">
          THis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsum.
        </div>
        <a href="#">Læs nyheden</a>
    </div>
    <div class="block-module--content-element-wrapper">
      <h3 class="block-module--content-label">
        <a href="#">Lorem ipsum lige her</a>
        </h2>
        <div class="block-module--content-element">
          THis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsumTHis is the purpose, lorem ipsum.
        </div>
        <a href="#">Læs nyheden</a>
    </div>
  </div>
</div>
