<div class="field-module--wrapper">
  <div class="field-module--label">Inspirationsmateriale</div>
  <div class="field-module--inspirational-material">
    <div class="field-module--inspirational-material-item">
      <div class="field-collection-module--description">"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed d</div>
      <div class="field-collection-module--litt">Lorem ipsum dolor sit amet, consectetur adipisicing elit,</div>
      <div class="field-collection-module--file">
        <a href="http://ulf.local/sites/default/files/material/changes_0.txt" type="text/plain; length=343048">changes.txt</a>
      </div>
      <div class="field-collection-module--link"><a href="http://google.com">dsda</a></div>
    </div>
    <div class="field-module--inspirational-material-item">
      <div class="field-collection-module--description">dsadad</div>
      <div class="field-collection-module--litt">dsadsa</div>
      <div class="field-collection-module--link"><a href="http://google.com">dsda</a></div>
    </div>
  </div>
</div>
