<div class="field-module--wrapper">
  <div class="field-module--label">Fag/læringsmål</div>
  <div class="field-module--text">
    <div class="field-module--items">
      <div class="field-module--item even">
        Hi omnes lingua, institutis, legibus inter se differunt. Morbi odio eros, volutpat ut pharetra
        vitae, lobortis sed nibh. Non equidem invideo, miror magis posuere velit aliquet. Fabio vel iudice
        vincam, sunt in culpa qui officia. Curabitur blandit tempus ardua ridiculus sed magna.
      </div>
    </div>
  </div>
  <div class="field-module--label">Aktiviteter</div>
  <div class="field-module--text">
    <div class="field-module--items">
      <div class="field-module--item even">dsda</div>
    </div>
  </div>
  <div class="field-module--label">Baggrundsviden</div>
  <div class="field-module--text">
    <div class="field-module--items">
      <div class="field-module--item even">adsd</div>
    </div>
  </div>
  <div class="field-module--label">Efterbehandling</div>
  <div class="field-module--text">
    <div class="field-module--items">
      <div class="field-module--item even">Ny test</div>
    </div>
  </div>
  <div class="field-module--label">Evt. forslag til forberedelse og/eller efterbehandling i daginstitutionen</div>
  <div class="field-module--text">
    <div class="field-module--items">
      <div class="field-module--item even">Ny test</div>
    </div>
  </div>
</div>
