<div class="block-module--wrapper is-last">
  <div class="layout-block-youth">
    <h2 class="teaser-module--header">Ungdomsuddannelsesforløb</h2>
    <div class="teaser-module--content">
      <article class="teaser-module--youth is-odd">
        <div class="teaser-module--inner">
          <img width="800" height="500" alt="" class="teaser-module--image" src="http://ulf.local/profiles/ulf/themes/ulftheme/mockups/mockup_images/doubtful_votes.jpg">
            <span class="teaser-module--text">
              <a href="/ungdomsuddannelse" class="teaser-module--label">Ungdomsuddannelse:</a><a href="/grundskole/ny-test" class="teaser-module--title">Rejsen til sol, måne og stjerner</a>
            </span>
        </div>
      </article>
      <article class="teaser-module--youth is-even">
        <div class="teaser-module--inner">
          <img width="800" height="500" alt="" class="teaser-module--image" src="http://ulf.local/profiles/ulf/themes/ulftheme/mockups/mockup_images/jump.jpg">
            <span class="teaser-module--text">
              <a href="/ungdomsuddannelse" class="teaser-module--label">Ungdomsuddannelse:</a><a href="/grundskole/ny-test" class="teaser-module--title">Rejsen til sol, måne og stjerner</a>
            </span>
        </div>
      </article>
    </div>
  </div>
</div>
