<div class="block-module--wrapper">
  <div class="layout-block-promoted">
    <h2 class="teaser-module--header">Populære forløb</h2>
    <div class="teaser-module--content">
      <article class="teaser-module--promoted">
        <div class="teaser-module--inner">
          <img width="800" height="500" alt="" class="teaser-module--image" src="http://ulf.local/profiles/ulf/themes/ulftheme/mockups/mockup_images/doubtful_votes.jpg">
          <span class="teaser-module--text">
            <a href="/ungdomsuddannelse" class="teaser-module--label">Ungdomsuddannelse:</a><a href="/grundskole/ny-test" class="teaser-module--title">Rejsen til sol, måne og stjerner</a>
          </span>
        </div>
      </article>
      <article class="teaser-module--promoted is-odd">
        <div class="teaser-module--inner">
          <img width="800" height="500" alt="" class="teaser-module--image" src="http://ulf.local/profiles/ulf/themes/ulftheme/mockups/mockup_images/jump.jpg">
          <span class="teaser-module--text">
            <a href="/ungdomsuddannelse" class="teaser-module--label">Dagtilbud:</a><a href="/grundskole/ny-test" class="teaser-module--title">Rejsen til sol, måne og stjerner</a>
          </span>
        </div>
      </article>
      <article class="teaser-module--promoted is-even">
        <div class="teaser-module--inner">
          <img width="800"  height="500" alt="" class="teaser-module--image" src="http://ulf.local/profiles/ulf/themes/ulftheme/mockups/mockup_images/Pumpkin-Pancakes1.jpg">
          <div class="teaser-module--text">
            <a href="/ungdomsuddannelse" class="teaser-module--label">Grundskole:</a><a href="/grundskole/ny-test" class="teaser-module--title">Rejsen til sol, måne og stjerner</a>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>
