<div class="page-content">
  <h1>Statisk side</h1>
  <p>Non equidem invideo, miror magis posuere velit aliquet. Tityre, tu patulae recubans sub tegmine fagi  dolor.
    Idque Caesaris facere voluntate liceret: sese habere. Tityre, tu patulae recubans sub tegmine fagi  dolor.
  </p>
  <p>Sed haec quis possit intrepidus aestimare tellus. Quam temere in vitiis, legem sancimus haerentia. Quam temere
    in vitiis, legem sancimus haerentia. Sed haec quis possit intrepidus aestimare tellus. Morbi fringilla convallis
    sapien, id pulvinar odio volutpat.
  </p>
  <p>
    Plura mihi bona sunt, inclinet, amari petere vellent. Nec dubitamus multa iter quae et nos invenerat. Ullamco
    laboris nisi ut aliquid ex ea commodi consequat. Tityre, tu patulae recubans sub tegmine fagi  dolor. Quisque ut
    dolor gravida, placerat libero vel, euismod. Phasellus laoreet lorem vel dolor tempus vehicula.
    At nos hinc posthac, sitientis piros Afros. Praeterea iter est quasdam res quas ex communi. Ut enim ad minim veniam,
    quis nostrud exercitation. Fabio vel iudice vincam, sunt in culpa qui officia.
  </p>
  <p>
    Inmensae subtilitatis, obscuris et malesuada fames. Fabio vel iudice vincam, sunt in culpa qui officia. Quisque
    placerat facilisis egestas cillum dolore. Qui ipsorum lingua Celtae, nostra Galli appellantur. Donec sed odio
    operae, eu vulputate felis rhoncus.
    Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae. Tu quoque, Brute, fili mi, nihil timor populi, nihil!
    Prima luce, cum quibus mons aliud  consensu ab eo. Cum sociis natoque penatibus et magnis dis parturient. Ab illo
    tempore, ab est sed immemorabili.
  </p>
  <p>
    Vivamus sagittis lacus vel augue laoreet rutrum faucibus. Sed haec quis possit intrepidus aestimare tellus. Tityre,
    tu patulae recubans sub tegmine fagi  dolor. Quisque ut dolor gravida, placerat libero vel, euismod. Quo usque
    tandem abutere, Catilina, patientia nostra? Fictum,  deserunt mollit anim laborum astutumque!
  </p>
  <ul class="pager">
    <li class="pager-current first">1</li>
    <li class="pager-item"><a href="#" title="Gå til side 2">2</a></li>
    <li class="pager-next"><a href="#" title="Gå til næste side">næste ›</a></li>
    <li class="pager-last last"><a href="#" title="Gå til sidste side">sidste »</a></li>
  </ul>
</div>
