<div class="page-content">
  <h1>Rejsen til solen, månen og stjernerne</h1>
  <div class="field-module--author">
    <span class="field-module--author--label">Arrangør:</span>
    <span class="field-module--author--value"><a href="user/1">Den Jyske Opera</a></span>
  </div>
  <div class="field-module--image">
    <div class="field-module--image-items">
      <div class="field-module--image-item is-odd"><img src="http://placehold.it/1000x300" width="770" height="224" alt=""></div>
    </div>
  </div>
  <div class="field-module--purpose">
    <div class="field-module--purpose-items">
      <div class="field-module--label">Formål med forløbet</div>
      <div class="field-module--purpose-item is-odd">
        At eleverne møder musik og fortælling i en integreret og kunstnerisk form. At eleverne med stemme
        og krop oplever musikkens udtrykskraft og herved får stimuleret deres fantasi og kulturelle
        oplevelsesparathed.
      </div>
    </div>
  </div>
  <div class="field-module--label">Beskrivelse</div>
  <div class="field-module--text">
    <div class="field-module--items">
      <div class="field-module--item even">
        Døren går op og børnene inviteres ind i et rum af fortælling, musik og billeder efter klassisk
        japansk kamishibai-tradition. Myter og fortællinger fra hele verden om solen, månen og stjernerne
        præsenteres i en poetisk, legende og aktivtfield-module--items inddragende form. Workshopforestillingen kan spilles enten
        på skolen eller på Den Jyske Opera efter nærmere aftale og kan efterfølgende naturligt inddrages i
        både dansk, billedkunst og musikundervisningen.
      </div>
    </div>
  </div>
  <div class="field-module--tags">
    <a href="/forloeb/testing" class="field-module--tags-item">Testing</a>
    <a href="/forloeb/content" class="field-module--tags-item">content</a>
  </div>
</div>
