<div class="page-content">
  <h1 class="page-title">HUSK temadag om ULF og folkeskolereformen for ULF-aktører den 16. januar 2014</h1>
  <div class="field-module--image">
    <div class="field-module--image-items">
      <div class="field-module--image-item is-odd"><img src="http://placehold.it/1000x300" width="770" height="224" alt=""></div>
    </div>
  </div>

  <h4>Formålet med dagen</h4>
  <p>
    1) At give ULF-aktørerne kendskab til nye rammer, samarbejds- og udviklingsmuligheder med Børn og Unge som følge af folkeskolereformen.
    2) At give ULF-aktørerne kendskab til og forståelse for argumenter for at fokusere på formidling i de alternative læringsrum til målgruppen 0-6-årige børn.
  </p>
  <h4>Tid</h4>
  <p>
    16. januar 2014 kl. 8.10-13.30
  </p>
</div>
