<div class="search-module--form-wrapper">
  <div class="search-module--form">
    <form class="search-form" action="/search/site/test" method="post" id="search-form" accept-charset="UTF-8">
      <div>
        <h1 class="page-title">Søgeresultat: Kulturhistorie</h1>
        <div class="container-inline form-wrapper" id="edit-basic">
          <div class="form-item form-type-textfield form-item-keys">
            <input type="text" id="edit-keys" name="keys" value="test" size="20" maxlength="255" class="form-text">
          </div>
          <input class="search-module--submit form-submit" type="submit" id="edit-submit" name="op" value="Search"><input type="hidden" name="get" value="[]">
        </div>
        <input type="hidden" name="form_build_id" value="form-VSrMXbvZh9pwg1N2yFHGiE1YysMlXRaHS1IE-hEIzXY">
        <input type="hidden" name="form_id" value="apachesolr_search_custom_page_search_form">
      </div>
    </form>
  </div>
  <div class="search-module--spelling-suggestions-wrapper">
    <div class="form-item">
      <span class="search-module--did-you-mean-text">Mente du:</span>
      <span>
        <a href="/search/site/text">text</a>
      </span>
    </div>
  </div>
  <div class="search-facets-mobile--toggle-wrapper">
    <div href="#" class="search-facets-mobile--toggle js-toggle-mobile-search-facets">Filtrér søgning</div>
  </div>
</div>

