<div class="search-facets contextual-links-region">
  <h2 class="block-inline-module--header">Filtrér søgning</h2>
  <div class="block-inline-module--content">
    <fieldset class="search-facets--group">
      <legend class="search-facets--header">Overordnet målgruppe</legend>
      <div class="search-facets--item">
        <input type="radio" name="audience" id="audience_1" class="search-facets--input">
        <label href="#" for="audience_1" class="search-facets--link">Dagtilbud</label>
      </div>
      <div class="search-facets--item">
        <input type="radio" name="audience" id="audience_2" class="search-facets--input">
        <label href="#" for="audience_2" class="search-facets--link">Grundskole</label>
      </div>
      <div class="search-facets--item">
        <input type="radio" name="audience" id="audience_3" class="search-facets--input">
        <label href="#" for="audience_3" class="search-facets--link">Ungdomsuddannelse</label>
      </div>
    </fieldset>
    <fieldset class="search-facets--group">
      <legend class="search-facets--header">Målgruppe</legend>
      <p class="search-facets--inactive-text">Vælg først overordnet målgruppe</p>
    </fieldset>
    <fieldset class="search-facets--group">
      <legend class="search-facets--header">Emne</legend>
      <div class="search-facets--item">
        <input type="checkbox" id="subject_1" class="search-facets--input">
        <label href="#" for="subject_1" class="search-facets--link">Kulturhistorie og kulturarv (2)</label>
      </div>
      <div class="search-facets--item">
        <input type="checkbox" id="subject_2" class="search-facets--input">
        <label href="#" for="subject_2" class="search-facets--link">Film, musik, teater og dans (1)</label>
      </div>
      <div class="search-facets--item">
        <input type="checkbox" id="subject_3" class="search-facets--input">
        <label href="#" for="subject_3" class="search-facets--link">Idræt og bevægelse (1)</label>
      </div>
    </fieldset>
    <fieldset class="search-facets--group">
      <legend class="search-facets--header">Tilbudstype</legend>
      <div class="search-facets--item">
        <input type="checkbox" id="course_type_1" class="search-facets--input">
        <label href="#" for="course_type_1" class="search-facets--link">Læringsforløb</label>
      </div>
      <div class="search-facets--item">
        <input type="checkbox" id="course_type_2" class="search-facets--input">
        <label href="#" for="course_type_2" class="search-facets--link">Dagsbesøg</label>
      </div>
    </fieldset>
    <fieldset class="search-facets--group">
      <legend class="search-facets--header">Vis kun</legend>
      <div class="search-facets--item">
        <input type="checkbox" id="special_1" class="search-facets--input">
        <label href="#" for="special_1" class="search-facets--link">Gratis forløb</label>
      </div>
    </fieldset>
    <fieldset class="search-facets--group">
      <legend class="search-facets--header">Type</legend>
      <div class="search-facets--item">
        <input type="radio" name="type" id="type_1" class="search-facets--input">
        <label href="#" for="type_1" class="search-facets--link">Dagtilbud</label>
      </div>
      <div class="search-facets--item">
        <input type="radio" name="type" id="type_2" class="search-facets--input">
        <label href="#" for="type_2" class="search-facets--link">Grundskole</label>
      </div>
    </fieldset>
  </div>
</div>
