<ul class="tabs primary">
  <li class="active">
    <a class="active" href="/fabio-vel-iudice-vincam-sunt-culpa-qui-officia-nihil-hic-munitissimus-habendi-senatus-locus-nihil">View<span class="element-invisible">(active tab)</span></a>
  </li>
  <li>
    <a href="/node/1/edit">Edit</a>
  </li>
</ul>
<ul class="tabs secondary">
  <li class="active">
    <a class="active" href="/fabio-vel-iudice-vincam-sunt-culpa-qui-officia-nihil-hic-munitissimus-habendi-senatus-locus-nihil">View<span class="element-invisible">(active tab)</span></a>
  </li>
  <li>
    <a href="/node/1/edit">Edit</a>
  </li>
</ul>