<header class="header" role="banner">
  <div class="header--inner">
    <div class="header--nav-wrapper">
      <a href="#" class="nav--toggle-header-search js-toggle-header-search"><img src="<?php echo $path_to_theme; ?>images/icon-search.png"></a>
      <a href="#" class="nav--toggle-mobile-nav js-toggle-mobile-nav"><img src="<?php echo $path_to_theme; ?>images/icon-menu.png"></a>
      <a href="/" class="logo"><img class="logo-image" src="<?php echo $path_to_theme; ?>/logo.png"></a>
    </div>
    <div class="header-search-module js-header-search">
      <div class="header-search-module--inner">
        <!-- Default drupal form.-->
        <form action="/user" method="post" id="search-block-form" accept-charset="UTF-8">
          <div>
            <div class="form-item form-type-searchfield form-item-search-block-form">
              <label class="element-invisible" for="edit-search-block-form--2"> </label>
              <input title="Enter the terms you wish to search for." type="search" id="edit-search-block-form--2" name="search_block_form" value="" size="15" maxlength="128" placeholder="Skriv f.eks. film, musik el. lign." class="form-text form-search">
            </div>
            <div class="form-actions form-wrapper" id="edit-actions">
              <input class="header-search-module--submit form-submit" type="submit" id="edit-submit" name="op" value="Search">
            </div>
            <input type="hidden" name="form_build_id" value="form-XjRtY06sH7wOUqUHn2D9AsafxYhKSiWlHk07tcdIkJs">
            <input type="hidden" name="form_token" value="Wfp9izR_d9LAJRmwwIUFVqKuQzXxTB77GALnIkcyMZA">
            <input type="hidden" name="form_id" value="search_block_form">
          </div>
        </form>
      </div>
    </div>
  </div>
</header>
<nav class="nav--mobile js-mobile-nav">
  <div class="nav--inner">
    <ul class="nav--list">
      <li class="nav--mobile-link"><a class="active" title="" href="/">Forside</a></li>
      <li class="nav--mobile-link"><a title="" href="/forloeb/dagtilbud">Dagtilbud</a></li>
      <li class="nav--mobile-link"><a title="" href="/forloeb/grundskole">Grundskole</a></li>
      <li class="nav--mobile-link"><a title="" href="/forloeb/ungdomsuddannelse">Ungdomsuddannelse</a></li>
    </ul>
  </div>
</nav>
<nav class="nav">
  <div class="nav--inner">
    <ul class="nav--list">
      <li class="nav--list-item"><a class="nav--list-link active" title="" href="/">Forside</a></li>
      <li class="nav--list-item"><a class="nav--list-link" title="" href="/forloeb/dagtilbud">Dagtilbud</a></li>
      <li class="nav--list-item"><a class="nav--list-link" title="" href="/forloeb/grundskole">Grundskole</a></li>
      <li class="nav--list-dropdown-item">
        <a class="nav--list-dropdown-link" title="" href="#">
          With sub
        </a>
        <div class="nav--dropdown-item">
          <a class="nav--dropdown-link" title="" href="#">Min konto</a>
          <a class="nav--dropdown-link" title="" href="#">Notifikationer</a>
          <a class="nav--dropdown-link" title="" href="#">Opret spørgsmål</a>
          <a class="nav--dropdown-link" title="" href="#">Log af</a>
        </div>
      </li>
      <li class="nav--list-dropdown-item">
        <a class="nav--list-dropdown-link" title="" href="#">
          Another
        </a>
        <div class="nav--dropdown-item">
          <a class="nav--dropdown-link" title="" href="#">Min konto</a>
          <a class="nav--dropdown-link" title="" href="#">Notifikationer</a>
          <a class="nav--dropdown-link" title="" href="#">Opret spørgsmål</a>
          <a class="nav--dropdown-link" title="" href="#">Log af</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
