<?php

/**
 * @file
 * Uninstall functions for the Better descriptions module.
 */

/**
 * Implements hook_uninstall().
 */
function better_field_descriptions_uninstall() {

  // Delete variables.
  variable_del('better_field_descriptions');
  variable_del('better_field_descriptions_settings');
  variable_del('better_field_descriptions_default_entity');
}

/**
 * Implements hook_uninstall().
 */
function better_field_descriptions_install() {
  // Set variables.
  variable_set('better_field_descriptions_default_entity', 'node');
}
