<?php
/**
 * @file
 * Code for the Ulf frontpage feature.
 */

include_once 'ulf_frontpage.features.inc';

/**
 * Implements hook_ctools_plugin_api().
 */
function ulf_frontpage_ctools_plugin_api($module, $api) {
  if ($module == "ctools_custom_content" && $api == "ctools_content") {
    return array("version" => "1");
  }
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}