<?php
/**
 * @file
 * ulf_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function ulf_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-BOiTNRybGi0EqoVhsAPq2yw0QL1EVZo1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BOiTNRybGi0EqoVhsAPq2yw0QL1EVZo1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -15,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-f5jleT4wQqSvPAZwM4ccmbfz6FrzLQzC'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'f5jleT4wQqSvPAZwM4ccmbfz6FrzLQzC',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -12,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-jPSEnykO74th5EozWmGpclG7Dd7euxNN'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'jPSEnykO74th5EozWmGpclG7Dd7euxNN',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ulf',
        'weight' => -13,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-sZSsaGJedCZ38yin8onDhbRjtJQH3g6C'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'sZSsaGJedCZ38yin8onDhbRjtJQH3g6C',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ulf',
        'weight' => -11,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-sropn1R1PQh1vJZB1Z6wtaoRZmEeCOge'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'sropn1R1PQh1vJZB1Z6wtaoRZmEeCOge',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -10,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-tPuYoiknARWJHIIgVsBEfQdSO6vRHC0S'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'tPuYoiknARWJHIIgVsBEfQdSO6vRHC0S',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -11,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-v30lLxmCsdkS0BHMDmyFE0mYS5hkePNV'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'v30lLxmCsdkS0BHMDmyFE0mYS5hkePNV',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ulf',
        'weight' => -12,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-vga1DhRgcg0BrGxTS3Gmzs1ZvkwvXo0t'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'vga1DhRgcg0BrGxTS3Gmzs1ZvkwvXo0t',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -15,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-zkQUMgh2adYg5SkgiravqOKciGZlFTxo'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'zkQUMgh2adYg5SkgiravqOKciGZlFTxo',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => 'facets',
        'status' => 1,
        'theme' => 'ulf',
        'weight' => -13,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['search_api_page-default'] = array(
    'cache' => 5,
    'custom' => 0,
    'delta' => 'default',
    'module' => 'search_api_page',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'ulf' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ulf',
        'weight' => -2,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
