<?php

/**
 * @file ulf_moderations.module.
 *
 * Change moderation tabs.
 */

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Add local task for quick comparison between draft and published.
 */
function ulf_moderations_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $selected_paths = array(
    'node/%',
    'node/%/edit',
    'node/%/draft',
    'node/%/revisions/view',
  );

  // Change tab on selected paths.
  if (in_array($root_path, $selected_paths)) {
    // Foreach tab.
    foreach($data['tabs']['0']['output'] as $key => $value) {

      // Check that we have the right tab.
      if ($value['#link']['title'] == 'Moderate') {

        // Change title.
        $data['tabs']['0']['output'][$key]['#link']['title'] = t('Compare draft to published content');

        // Set active.
        if($root_path ==  'node/%/revisions/view') {
          $data['tabs']['0']['output'][$key]['#active'] = TRUE;
        }

        // Set path if it is available (requires a published version and a current version of the node), else remove the compare tab entirely.
        if(!empty($router_item['map']['1']->workbench_moderation['published']->vid) && !empty($router_item['map']['1']->workbench_moderation['current'])) {
          $published_vid = $router_item['map']['1']->workbench_moderation['published']->vid;
          $draft_vid = $router_item['map']['1']->workbench_moderation['current']->vid;
          $data['tabs']['0']['output'][$key]['#link']['href'] = $data['tabs']['0']['output'][$key]['#link']['tab_root_href'] . '/revisions/view/' . $published_vid . '/' . $draft_vid;
        } else {
          unset($data['tabs']['0']['output'][$key]);
        }
      }
    }
  }
}