<?php

/**
 * @file
 */

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Add local task for quick comparison between draft and published.
 */
function ulf_moderations_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $selected_paths = array(
    'node/%',
    'node/%/edit',
    'node/%/draft',
    'node/%/revisions/view',
  );

  if (in_array($root_path, $selected_paths)) {
    // Hide original moderation tab.
    foreach($data['tabs']['0']['output'] as $key => $value) {
      if ($value['#link']['title'] == 'Moderate') {
        $data['tabs']['0']['output'][$key]['#link']['title'] = t('Compare draft to published content');
        if($root_path ==  'node/%/revisions/view') {
          $data['tabs']['0']['output'][$key]['#active'] = TRUE;
        }
        if(!empty($router_item['map']['1']->workbench_moderation['published']->vid) && !empty($router_item['map']['1']->workbench_moderation['current'])) {
          $published_vid = $router_item['map']['1']->workbench_moderation['published']->vid;
          $draft_vid = $router_item['map']['1']->workbench_moderation['current']->vid;
          $data['tabs']['0']['output'][$key]['#link']['href'] = $data['tabs']['0']['output'][$key]['#link']['tab_root_href'] . '/revisions/view/' . $published_vid . '/' . $draft_vid;
        } else {
          unset($data['tabs']['0']['output'][$key]);
        }
      }
    }
  }
}