<?php
/**
 * @file
 * Defines migration groups and what to migrate.
 */

/**
 * Implements hook_migrate_api().
 */
function ulf_migration_migrate_api() {
  // Define migration groups.
  $api = array(
    'api' => 2,
    'groups' => array(
      'ulf_files' => array(
        'title' => t('Files'),
      ),
      'ulf_users' => array(
        'title' => t('Users'),
      ),
      'ulf_content' => array(
        'title' => t('Content'),
      ),
    ),
    'migrations' => array(
      // Files.
      'UlfFiles' => array(
        'class_name' => 'UlfFilesMigration',
        'group_name' => 'ulf_files',
      ),
      // Roles.
      'UlfRoles' => array(
        'class_name' => 'UlfRolesMigration',
        'group_name' => 'ulf_users',
      ),
      // Users contact field collection.
      'UlfUsersContact' => array(
        'class_name' => 'UlfUsersContactMigration',
        'group_name' => 'ulf_users',
      ),

      // Users.
      'UlfUsers' => array(
        'class_name' => 'UlfUsersMigration',
        'group_name' => 'ulf_users',
      ),

      // Taxonomies.


      // Static pages (omulf).
      'UlfStatic' => array(
        'class_name' => 'UlfStaticMigration',
        'group_name' => 'ulf_content',
      ),

      // News.
      'UlfNews' => array(
        'class_name' => 'UlfNewsMigration',
        'group_name' => 'ulf_content',
      ),

      // course-educators
      'UlfCoursesEducation' => array(
        'class_name' => 'UlfCoursesEducationMigration',
        'group_name' => 'ulf_content',
      ),

      // course-educators.


      // course.

    ),
    'field handlers' => array(
      'DateMigrateFieldHandler',
    ),
  );

  return $api;
}