<?php
/**
 * @file
 * Defines migration groups and what to migrate.
 */

/**
 * Implements hook_migrate_api().
 */
function ulf_migration_migrate_api() {
  // Define migration groups.
  $api = array(
    'api' => 2,
    'groups' => array(
      'ulf_files' => array(
        'title' => t('Files'),
      ),
      'ulf_users' => array(
        'title' => t('Users'),
      ),
    ),
    'migrations' => array(
      // Files.
      'UlfFiles' => array(
        'class_name' => 'UlfFilesMigration',
        'group_name' => 'ulf_files',
      ),
      // Users.
      'UlfUsers' => array(
        'class_name' => 'UlfUsersMigration',
        'group_name' => 'ulf_users',
      ),



      // Taxonomies.


      // Static pages. (omulf)


      // news.

      // course-educators.


      // course.

    ),
    'field handlers' => array(
      'DateMigrateFieldHandler',
    ),
  );

  return $api;
}