<?php

/**
 * @file
 * Code for the Ulf World targets feature.
 */

include_once 'ulf_world_targets.features.inc';

function ulf_world_targets_theme($existing, $type, $theme, $path) {
  $module_path = drupal_get_path('module', 'ulf_world_targets');

  return [
    'world_targets' => [
      'variables' => [
        'world_targets' => [],
      ],
      'template' => 'world-targets',
      'path' => $module_path . '/templates',
    ],
  ];
}

function ulf_world_targets_preprocess_world_targets(&$variables) {
  if (empty($variables['world_targets'])) {
    return FALSE;
  }

  drupal_add_css(
    drupal_get_path('module', 'ulf_world_targets')
    . '/css/ulf_world_targets.css'
  );

  $world_targets_images = [
    '1' => 'no_poverty.png',
    '2' => 'zero_hunger.png',
    '3' => 'good_health.png',
    '4' => 'quality_education.png',
    '5' => 'gender_equality.png',
    '6' => 'clean_water.png',
    '7' => 'clean_energy.png',
    '8' => 'economic_growth.png',
    '9' => 'innovation.png',
    '10' => 'reduced_inequality.png',
    '11' => 'sustainable_cities.png',
    '12' => 'responsible_consumption.png',
    '13' => 'climate_action.png',
    '14' => 'life_below_water.png',
    '15' => 'life_on_land.png',
    '16' => 'strong_institutions.png',
    '17' => 'partnerships.png',
  ];

  $image_url = base_path() . drupal_get_path('module', 'ulf_world_targets')
    . '/images';

  $world_targets = [];
  foreach ($variables['world_targets'] as $target) {
    $target = $target['value'];
    $image = theme(
      'image', [
      'path' => $image_url . '/' . $world_targets_images[$target],
    ]
    );

    $world_targets[] = l(
      $image, 'https://www.verdensmaalene.dk/maal/' . $target,
      [
        'html' => TRUE,
        'attributes' => ['target' => '_blank'],
      ]
    );
  }

  $variables['world_targets'] = $world_targets;
}

function ulf_world_targets_preprocess_node(&$variables) {

  if (isset($variables['field_world_targets'])) {
    $world_targets = $variables['field_world_targets'][LANGUAGE_NONE] ?? ($variables['field_world_targets'] ?? []);

    if (!empty($world_targets)) {
      try {
        $variables['world_targets'] = theme(
          'world_targets', [
            'world_targets' => $world_targets,
          ]
        );
      } catch (Exception $e) {
        watchdog('world_targets', $e->getMessage(), WATCHDOG_WARNING);
      }
    }
  }

}

function ulf_world_targets_preprocess_user_profile(&$variables) {
  $account = $variables['elements']['#account'];

  if (isset($account->field_world_targets)) {
    $world_targets = $account->field_world_targets[LANGUAGE_NONE] ?? ($account->field_world_targets ?? []);

    if (!empty($world_targets)) {
      try {
        $variables['world_targets'] = theme(
          'world_targets', [
            'world_targets' => $world_targets,
          ]
        );
      } catch (Exception $e) {
        watchdog('world_targets', $e->getMessage(), WATCHDOG_WARNING);
      }
    }
  }

}
